SELECT
    CUSTOM_ACTIVITY,
    CUSTOM_ACTIVITY_OUTCOME,
    COUNT(*) AS TOTAL
FROM SILVER.LEADS_ACTIVITIES_SUMMARY
WHERE CUSTOM_ACTIVITY IN (
    '5) Strategy Call',
    '6) Strategy Call Follow Up'
)
GROUP BY 1,2
ORDER BY CUSTOM_ACTIVITY, TOTAL DESC;

SELECT
    LEAD_ID,
    ACTIVITY_ID,
    CUSTOM_ACTIVITY,
    CUSTOM_ACTIVITY_OUTCOME,
    DEA_INTERNAL_EMAIL,
    DEA_INTERNAL_NAME,
    ACTIVITY_AT,
    STATUS_CHANGE
FROM SILVER.LEADS_ACTIVITIES_SUMMARY
WHERE CUSTOM_ACTIVITY IN (
    '5) Strategy Call',
    '6) Strategy Call Follow Up'
)
LIMIT 50;

SELECT
    CUSTOM_ACTIVITY,
    COUNT(*) AS TOTAL_ROWS,
    COUNT_IF(CUSTOM_ACTIVITY_OUTCOME IS NOT NULL) AS OUTCOME_ROWS,
    COUNT_IF(CLOSER_EMAIL IS NOT NULL) AS CLOSER_ROWS,
    COUNT_IF(SETTER_EMAIL IS NOT NULL) AS SETTER_ROWS,
    COUNT_IF(OFFER_PRESENTED IS NOT NULL) AS OFFER_ROWS
FROM SALES_ANALYTICS_DB.SILVER.LEADS_ACTIVITIES_SUMMARY
WHERE CUSTOM_ACTIVITY IN (
    '5) Strategy Call',
    '6) Strategy Call Follow Up'
)
GROUP BY CUSTOM_ACTIVITY
ORDER BY CUSTOM_ACTIVITY;

SELECT
    LEAD_ID,
    ACTIVITY_ID,
    CUSTOM_ACTIVITY,
    STATUS_CHANGE,
    CUSTOM_ACTIVITY_OUTCOME,
    CLOSER_EMAIL,
    CLOSER_NAME,
    SETTER_EMAIL,
    SETTER_NAME,
    OFFER_PRESENTED,
    ACTIVITY_AT
FROM SALES_ANALYTICS_DB.SILVER.LEADS_ACTIVITIES_SUMMARY
WHERE CUSTOM_ACTIVITY = '6) Strategy Call Follow Up'
LIMIT 50;


USE DATABASE SALES_ANALYTICS_DB;
USE SCHEMA GOLD;

CREATE OR REPLACE VIEW GOLD.ALL_STRATEGIES_DETAILS AS
SELECT
    LEAD_ID,

    ACTIVITY_AT::DATE AS ACTIVITY_LOG_DATE,

    CUSTOM_ACTIVITY,

    -- CRM record status, such as published or draft
    STATUS_CHANGE AS STATUS,

    CLOSER_EMAIL,
    CLOSER_NAME,

    -- Populated for Strategy Calls;
    -- naturally NULL for Strategy Call Follow Ups
    CUSTOM_ACTIVITY_OUTCOME AS STRATEGY_CALL_OUTCOME,

    ACTIVITY_AT::DATE AS DATE_OF_STRATEGY_CALL,

    OFFER_PRESENTED,

    -- SME model uses SETTER plus SETTER_NAME.
    -- SETTER is represented by the setter's email.
    SETTER_EMAIL AS SETTER,
    SETTER_NAME

FROM SALES_ANALYTICS_DB.SILVER.LEADS_ACTIVITIES_SUMMARY
WHERE CUSTOM_ACTIVITY IN (
    '5) Strategy Call',
    '6) Strategy Call Follow Up'
);


SELECT COUNT(*) AS ALL_STRATEGIES_DETAILS_COUNT
FROM GOLD.ALL_STRATEGIES_DETAILS;
-- ans 4937
SELECT * 
FROM GOLD.ALL_STRATEGIES_DETAILS;

SELECT
    CUSTOM_ACTIVITY,
    COUNT(*) AS GOLD_ROWS
FROM GOLD.ALL_STRATEGIES_DETAILS
GROUP BY CUSTOM_ACTIVITY
ORDER BY CUSTOM_ACTIVITY;

SELECT
    CUSTOM_ACTIVITY,
    STRATEGY_CALL_OUTCOME,
    COUNT(*) AS TOTAL
FROM GOLD.ALL_STRATEGIES_DETAILS
GROUP BY
    CUSTOM_ACTIVITY,
    STRATEGY_CALL_OUTCOME
ORDER BY
    CUSTOM_ACTIVITY,
    TOTAL DESC;

    SELECT
    CUSTOM_ACTIVITY,
    COUNT(*) AS TOTAL_ROWS,
    COUNT_IF(CLOSER_EMAIL IS NOT NULL) AS CLOSER_ROWS,
    COUNT_IF(SETTER IS NOT NULL) AS SETTER_ROWS,
    COUNT_IF(OFFER_PRESENTED IS NOT NULL) AS OFFER_ROWS,
    COUNT_IF(STRATEGY_CALL_OUTCOME IS NOT NULL) AS OUTCOME_ROWS
FROM GOLD.ALL_STRATEGIES_DETAILS
GROUP BY CUSTOM_ACTIVITY
ORDER BY CUSTOM_ACTIVITY;

SELECT
    (SELECT COUNT(*)
     FROM SILVER.LEADS_ACTIVITIES_SUMMARY
     WHERE CUSTOM_ACTIVITY IN (
         '5) Strategy Call',
         '6) Strategy Call Follow Up'
     )) AS SILVER_ROWS,

    (SELECT COUNT(*)
     FROM GOLD.ALL_STRATEGIES_DETAILS) AS GOLD_ROWS;