USE DATABASE SALES_ANALYTICS_DB;
USE SCHEMA BRONZE;

CREATE OR REPLACE FILE FORMAT JSON_FF
TYPE = JSON
STRIP_OUTER_ARRAY = FALSE;

CREATE OR REPLACE STAGE SALES_ANALYTICS_RAW_STAGE
URL = 's3://sales-analytics-raw-aqib-test/'
STORAGE_INTEGRATION = SALES_ANALYTICS_S3_INT
FILE_FORMAT = JSON_FF;

LIST @SALES_ANALYTICS_RAW_STAGE;

COPY INTO CUSTOM_ACTIVITIES_RAW (JSON_OBJECT, INSERT_DATE)
FROM (
    SELECT
        $1,
        CURRENT_TIMESTAMP()
    FROM @SALES_ANALYTICS_RAW_STAGE/custom_activities_raw/
)
FILE_FORMAT = JSON_FF
ON_ERROR = CONTINUE;

SELECT COUNT(*) FROM CUSTOM_ACTIVITIES_RAW;

SELECT * 
FROM CUSTOM_ACTIVITIES_RAW
LIMIT 5;

CREATE OR REPLACE TABLE LEADS_RAW
(
    JSON_OBJECT VARIANT,
    INSERT_DATE TIMESTAMP_NTZ
);

COPY INTO LEAD_ACTIVITIES_RAW (JSON_OBJECT, INSERT_DATE)
FROM (
    SELECT
        $1,
        CURRENT_TIMESTAMP()
    FROM @SALES_ANALYTICS_RAW_STAGE/lead_activities_raw/
)
FILE_FORMAT = JSON_FF
ON_ERROR = CONTINUE;

COPY INTO CLOSE_CRM_USERS_RAW (JSON_OBJECT, INSERT_DATE)
FROM (
    SELECT
        $1,
        CURRENT_TIMESTAMP()
    FROM @SALES_ANALYTICS_RAW_STAGE/close_crm_users_raw/
)
FILE_FORMAT = JSON_FF
ON_ERROR = CONTINUE;

COPY INTO LEADS_RAW (JSON_OBJECT, INSERT_DATE)
FROM (
    SELECT
        $1,
        CURRENT_TIMESTAMP()
    FROM @SALES_ANALYTICS_RAW_STAGE/leads_raw/
)
FILE_FORMAT = JSON_FF
ON_ERROR = CONTINUE;

SELECT COUNT(*) FROM LEADS_RAW; # 397842

SELECT COUNT(*) FROM LEAD_ACTIVITIES_RAW; #379946

SELECT COUNT(*) FROM CLOSE_CRM_USERS_RAW; #20963

SELECT * FROM CLOSE_CRM_USERS_RAW limit 20; #20963


SELECT COUNT(*) FROM CUSTOM_ACTIVITIES_RAW; #43
SELECT * FROM CUSTOM_ACTIVITIES_RAW limit 20;
SELECT
    JSON_OBJECT
FROM BRONZE.CLOSE_CRM_USERS_RAW
LIMIT 5;

SELECT
    JSON_OBJECT:id::STRING AS USER_ID,
    JSON_OBJECT:email::STRING AS EMAIL,
    JSON_OBJECT:first_name::STRING AS FIRST_NAME,
    JSON_OBJECT:last_name::STRING AS LAST_NAME,
    JSON_OBJECT:date_created::TIMESTAMP_NTZ AS DATE_CREATED,
    JSON_OBJECT:date_updated::TIMESTAMP_NTZ AS DATE_UPDATED,
    MD5(
        COALESCE(JSON_OBJECT:id::STRING, '') ||
        COALESCE(JSON_OBJECT:email::STRING, '') ||
        COALESCE(JSON_OBJECT:first_name::STRING, '') ||
        COALESCE(JSON_OBJECT:last_name::STRING, '') ||
        COALESCE(JSON_OBJECT:date_updated::STRING, '')
    ) AS MD5_HASH,
    INSERT_DATE,
    CURRENT_TIMESTAMP() AS UPDATE_DATE
FROM BRONZE.CLOSE_CRM_USERS_RAW
LIMIT 10;


Select * from LEAD_ACTIVITIES_RAW
limit 100;

SELECT
    JSON_OBJECT,
    OBJECT_KEYS(JSON_OBJECT),
    JSON_OBJECT:raw_data,
    OBJECT_KEYS(JSON_OBJECT:raw_data)
FROM BRONZE.CLOSE_CRM_USERS_RAW
LIMIT 5;

SELECT COUNT(*)
FROM BRONZE.CLOSE_CRM_USERS_RAW r,
LATERAL FLATTEN(INPUT => r.JSON_OBJECT:raw_data:data) user_obj;

SELECT COUNT(*)
FROM BRONZE.CLOSE_CRM_USERS_RAW r,
LATERAL FLATTEN(INPUT => r.JSON_OBJECT:data) user_obj;


SELECT
    TRY_PARSE_JSON(
        REPLACE(JSON_OBJECT:raw_data:JSON_OBJECT::STRING, '''', '"')
    ) AS parsed_json
FROM BRONZE.CLOSE_CRM_USERS_RAW
LIMIT 5;

SELECT COUNT(*)
FROM BRONZE.CLOSE_CRM_USERS_RAW r,
LATERAL FLATTEN(
    INPUT => TRY_PARSE_JSON(
        REPLACE(r.JSON_OBJECT:raw_data:JSON_OBJECT::STRING, '''', '"')
    ):data
) user_obj;

LATERAL FLATTEN(INPUT => r.JSON_OBJECT:raw_data:data) user_obj;

TRUNCATE TABLE BRONZE.CUSTOM_ACTIVITIES_RAW;

COPY INTO BRONZE.CUSTOM_ACTIVITIES_RAW
FROM @YOUR_STAGE/custom_activities_raw/load_type=full/
FILE_FORMAT = (TYPE = JSON)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

TRUNCATE TABLE CUSTOM_ACTIVITIES_RAW;

COPY INTO CUSTOM_ACTIVITIES_RAW (JSON_OBJECT, INSERT_DATE)
FROM (
    SELECT
        $1,
        CURRENT_TIMESTAMP()
    FROM @SALES_ANALYTICS_RAW_STAGE/custom_activities_raw/load_type=full/
)
FILE_FORMAT = JSON_FF
ON_ERROR = CONTINUE;

SELECT COUNT(*)
FROM CUSTOM_ACTIVITIES_RAW;

SELECT
    JSON_OBJECT:raw_data:JSON_OBJECT:data[0]:id::STRING AS ACTIVITY_TYPE_ID,
    JSON_OBJECT:raw_data:JSON_OBJECT:data[0]:name::STRING AS ACTIVITY_NAME,
    JSON_OBJECT:glue_cleaned_flag::BOOLEAN AS GLUE_CLEANED_FLAG
FROM CUSTOM_ACTIVITIES_RAW
LIMIT 5;


SELECT
    JSON_OBJECT,
    INSERT_DATE
FROM LEAD_ACTIVITIES_RAW
LIMIT 5;

SELECT
    JSON_OBJECT
FROM LEAD_ACTIVITIES_RAW
WHERE JSON_OBJECT::STRING ILIKE '%custom.%'
LIMIT 10;

SELECT
    JSON_OBJECT
FROM LEAD_ACTIVITIES_RAW
WHERE JSON_OBJECT::STRING ILIKE '%Triage Call Outcome%'
   OR JSON_OBJECT::STRING ILIKE '%Strategy Call Outcome%'
   OR JSON_OBJECT::STRING ILIKE '%Offer Presented%'
   OR JSON_OBJECT::STRING ILIKE '%Contract Value%'
   OR JSON_OBJECT::STRING ILIKE '%Cash Collected%'
   OR JSON_OBJECT::STRING ILIKE '%Objections Faced%'
LIMIT 10;


SELECT
    JSON_OBJECT,
    INSERT_DATE
FROM CUSTOM_ACTIVITIES_RAW
LIMIT 5;


SELECT
    JSON_OBJECT
FROM CUSTOM_ACTIVITIES_RAW
WHERE JSON_OBJECT::STRING ILIKE '%Triage Call Outcome%'
   OR JSON_OBJECT::STRING ILIKE '%Strategy Call Outcome%'
   OR JSON_OBJECT::STRING ILIKE '%Offer Presented%'
   OR JSON_OBJECT::STRING ILIKE '%Contract Value%'
   OR JSON_OBJECT::STRING ILIKE '%Cash Collected%'
   OR JSON_OBJECT::STRING ILIKE '%Objections Faced%'
LIMIT 10;


SELECT
    JSON_OBJECT
FROM CUSTOM_ACTIVITIES_RAW
WHERE JSON_OBJECT::STRING ILIKE '%fields%'
LIMIT 10;


CREATE OR REPLACE TABLE CUSTOM_ACTIVITY_FIELDS AS
SELECT
    ACTIVITY.VALUE:id::STRING AS CUSTOM_ACTIVITY_ID,
    ACTIVITY.VALUE:name::STRING AS CUSTOM_ACTIVITY_NAME,

    FIELD.VALUE:id::STRING AS FIELD_ID,
    FIELD.VALUE:name::STRING AS FIELD_NAME,
    FIELD.VALUE:type::STRING AS FIELD_TYPE,
    FIELD.VALUE:required::BOOLEAN AS IS_REQUIRED,
    FIELD.VALUE:accepts_multiple_values::BOOLEAN AS ACCEPTS_MULTIPLE_VALUES,

    MD5(
        CONCAT_WS('|',
            ACTIVITY.VALUE:id::STRING,
            FIELD.VALUE:id::STRING,
            FIELD.VALUE:name::STRING,
            FIELD.VALUE:type::STRING
        )
    ) AS MD5_HASH,

    CURRENT_TIMESTAMP() AS INSERT_DATE,
    CURRENT_TIMESTAMP() AS UPDATE_DATE

FROM CUSTOM_ACTIVITIES_RAW R,
LATERAL FLATTEN(INPUT => R.JSON_OBJECT:raw_data:JSON_OBJECT:data) ACTIVITY,
LATERAL FLATTEN(INPUT => ACTIVITY.VALUE:fields) FIELD;

DROP TABLE IF EXISTS CUSTOM_ACTIVITY_FIELDS

USE DATABASE SALES_ANALYTICS_DB;
USE SCHEMA BRONZE;

WITH ACTIVITY_DEFINITIONS AS (
    SELECT
        activity.value:id::STRING AS CUSTOM_ACTIVITY_ID,
        activity.value:name::STRING AS CUSTOM_ACTIVITY_NAME,
        activity.value:fields AS FIELDS
    FROM SALES_ANALYTICS_DB.BRONZE.CUSTOM_ACTIVITIES_RAW r,
    LATERAL FLATTEN(
        INPUT => r.JSON_OBJECT:raw_data:data
    ) activity
)

SELECT
    a.CUSTOM_ACTIVITY_ID,
    a.CUSTOM_ACTIVITY_NAME,
    field.value:id::STRING AS FIELD_ID,
    field.value:name::STRING AS FIELD_NAME,
    field.value:type::STRING AS FIELD_TYPE,
    field.value:required::BOOLEAN AS IS_REQUIRED,
    field.value AS FIELD_DEFINITION
FROM ACTIVITY_DEFINITIONS a,
LATERAL FLATTEN(INPUT => a.FIELDS) field
WHERE a.CUSTOM_ACTIVITY_NAME IN (
    '1) Prospecting Activity',
    '2) Prospecting Follow Up'
)
ORDER BY
    a.CUSTOM_ACTIVITY_NAME,
    FIELD_NAME;

    WITH ACTIVITY_DEFINITIONS AS (
    SELECT
        activity.value:id::STRING AS CUSTOM_ACTIVITY_ID,
        activity.value:name::STRING AS CUSTOM_ACTIVITY_NAME,
        activity.value:fields AS FIELDS
    FROM SALES_ANALYTICS_DB.BRONZE.CUSTOM_ACTIVITIES_RAW r,
    LATERAL FLATTEN(
        INPUT => r.JSON_OBJECT:raw_data:data
    ) activity
)

SELECT
    a.CUSTOM_ACTIVITY_NAME,
    field.value:id::STRING AS FIELD_ID,
    field.value:name::STRING AS FIELD_NAME,
    field.value:type::STRING AS FIELD_TYPE,
    field.value AS FIELD_DEFINITION
FROM ACTIVITY_DEFINITIONS a,
LATERAL FLATTEN(INPUT => a.FIELDS) field
WHERE a.CUSTOM_ACTIVITY_NAME IN (
    '1) Prospecting Activity',
    '2) Prospecting Follow Up'
)
AND (
       field.value:name::STRING ILIKE '%outcome%'
    OR field.value:name::STRING ILIKE '%strategy%'
    OR field.value:name::STRING ILIKE '%scheduled%'
    OR field.value:name::STRING ILIKE '%status%'
    OR field.value:name::STRING ILIKE '%pipeline%'
)
ORDER BY
    a.CUSTOM_ACTIVITY_NAME,
    FIELD_NAME;


     SELECT DISTINCT
    activity.value:name::STRING AS CUSTOM_ACTIVITY_NAME
FROM SALES_ANALYTICS_DB.BRONZE.CUSTOM_ACTIVITIES_RAW r,
LATERAL FLATTEN(
    INPUT => r.JSON_OBJECT:raw_data:data
) activity
ORDER BY CUSTOM_ACTIVITY_NAME;

SELECT
    JSON_OBJECT
FROM SALES_ANALYTICS_DB.BRONZE.CUSTOM_ACTIVITIES_RAW
LIMIT 1;

SELECT
    OBJECT_KEYS(JSON_OBJECT) AS ROOT_KEYS
FROM SALES_ANALYTICS_DB.BRONZE.CUSTOM_ACTIVITIES_RAW
LIMIT 1;

SELECT
    TYPEOF(JSON_OBJECT:raw_data) AS RAW_TYPE,
    OBJECT_KEYS(JSON_OBJECT:raw_data) AS RAW_KEYS
FROM SALES_ANALYTICS_DB.BRONZE.CUSTOM_ACTIVITIES_RAW
LIMIT 1;

USE DATABASE SALES_ANALYTICS_DB;
USE SCHEMA BRONZE;

WITH ACTIVITY_DEFINITIONS AS (
    SELECT
        activity.value:id::STRING AS CUSTOM_ACTIVITY_ID,
        activity.value:name::STRING AS CUSTOM_ACTIVITY_NAME,
        activity.value:fields AS FIELDS
    FROM SALES_ANALYTICS_DB.BRONZE.CUSTOM_ACTIVITIES_RAW r,
    LATERAL FLATTEN(
        INPUT => r.JSON_OBJECT:raw_data:JSON_OBJECT:data
    ) activity
)

SELECT
    CUSTOM_ACTIVITY_ID,
    CUSTOM_ACTIVITY_NAME
FROM ACTIVITY_DEFINITIONS
ORDER BY CUSTOM_ACTIVITY_NAME;


WITH ACTIVITY_DEFINITIONS AS (
    SELECT
        activity.value:id::STRING AS CUSTOM_ACTIVITY_ID,
        activity.value:name::STRING AS CUSTOM_ACTIVITY_NAME,
        activity.value:fields AS FIELDS
    FROM SALES_ANALYTICS_DB.BRONZE.CUSTOM_ACTIVITIES_RAW r,
    LATERAL FLATTEN(
        INPUT => r.JSON_OBJECT:raw_data:JSON_OBJECT:data
    ) activity
)

SELECT
    CUSTOM_ACTIVITY_ID,
    CUSTOM_ACTIVITY_NAME
FROM ACTIVITY_DEFINITIONS
WHERE CUSTOM_ACTIVITY_NAME ILIKE '%prospect%'
   OR CUSTOM_ACTIVITY_NAME ILIKE '%outbound%'
ORDER BY CUSTOM_ACTIVITY_NAME;

WITH ACTIVITY_DEFINITIONS AS (
    SELECT
        activity.value:id::STRING AS CUSTOM_ACTIVITY_ID,
        activity.value:name::STRING AS CUSTOM_ACTIVITY_NAME,
        activity.value:fields AS FIELDS
    FROM SALES_ANALYTICS_DB.BRONZE.CUSTOM_ACTIVITIES_RAW r,
    LATERAL FLATTEN(
        INPUT => r.JSON_OBJECT:raw_data:JSON_OBJECT:data
    ) activity
)

SELECT
    a.CUSTOM_ACTIVITY_ID,
    a.CUSTOM_ACTIVITY_NAME,
    field.value:id::STRING AS FIELD_ID,
    field.value:name::STRING AS FIELD_NAME,
    field.value:type::STRING AS FIELD_TYPE,
    field.value:required::BOOLEAN AS IS_REQUIRED,
    field.value AS FIELD_DEFINITION
FROM ACTIVITY_DEFINITIONS a,
LATERAL FLATTEN(INPUT => a.FIELDS) field
WHERE a.CUSTOM_ACTIVITY_NAME IN (
    '1) Prospecting Activity',
    '2) Prospecting Follow Up'
)
ORDER BY
    a.CUSTOM_ACTIVITY_NAME,
    FIELD_NAME;

    WITH ACTIVITY_DEFINITIONS AS (
    SELECT
        activity.value:id::STRING AS CUSTOM_ACTIVITY_ID,
        activity.value:name::STRING AS CUSTOM_ACTIVITY_NAME,
        activity.value:fields AS FIELDS
    FROM SALES_ANALYTICS_DB.BRONZE.CUSTOM_ACTIVITIES_RAW r,
    LATERAL FLATTEN(
        INPUT => r.JSON_OBJECT:raw_data:JSON_OBJECT:data
    ) activity
)

SELECT
    a.CUSTOM_ACTIVITY_NAME,
    field.value:id::STRING AS FIELD_ID,
    field.value:name::STRING AS FIELD_NAME,
    field.value:type::STRING AS FIELD_TYPE,
    field.value AS FIELD_DEFINITION
FROM ACTIVITY_DEFINITIONS a,
LATERAL FLATTEN(INPUT => a.FIELDS) field
WHERE a.CUSTOM_ACTIVITY_NAME IN (
    '1) Prospecting Activity',
    '2) Prospecting Follow Up'
)
AND (
       field.value:name::STRING ILIKE '%outcome%'
    OR field.value:name::STRING ILIKE '%strategy%'
    OR field.value:name::STRING ILIKE '%scheduled%'
    OR field.value:name::STRING ILIKE '%status%'
    OR field.value:name::STRING ILIKE '%pipeline%'
)
ORDER BY
    a.CUSTOM_ACTIVITY_NAME,
    FIELD_NAME;

    SELECT
    activity.value:id::STRING AS ACTIVITY_ID,
    activity.value:lead_id::STRING AS LEAD_ID,
    activity.value:custom_activity_type_id::STRING AS CUSTOM_ACTIVITY_ID,

    activity.value:
        "custom.cf_Q2fsrD8VpPaunZLtyiy7P3vG6qJTv0w1ESmlhdHU2ra"
        ::STRING AS PROSPECTING_CALL_OUTCOME,

    activity.value:activity_at::TIMESTAMP_NTZ AS ACTIVITY_AT,
    activity.value:date_updated::TIMESTAMP_NTZ AS DATE_UPDATED

FROM SALES_ANALYTICS_DB.BRONZE.LEAD_ACTIVITIES_RAW r,
LATERAL FLATTEN(
    INPUT => r.JSON_OBJECT:raw_data:data
) activity

WHERE activity.value:
    "custom.cf_Q2fsrD8VpPaunZLtyiy7P3vG6qJTv0w1ESmlhdHU2ra"
    IS NOT NULL

QUALIFY ROW_NUMBER() OVER (
    PARTITION BY
        activity.value:lead_id::STRING,
        activity.value:id::STRING
    ORDER BY
        activity.value:activity_at::TIMESTAMP_NTZ DESC,
        activity.value:date_updated::TIMESTAMP_NTZ DESC,
        r.JSON_OBJECT:insert_date::TIMESTAMP_NTZ DESC
) = 1

LIMIT 100;