SELECT
    JSON_OBJECT
FROM BRONZE.CUSTOM_ACTIVITIES_RAW
LIMIT 5;

SELECT
    OBJECT_KEYS(JSON_OBJECT)
FROM BRONZE.CUSTOM_ACTIVITIES_RAW
LIMIT 5;


-- Path 1
SELECT COUNT(*)
FROM BRONZE.CUSTOM_ACTIVITIES_RAW r,
LATERAL FLATTEN(INPUT => r.JSON_OBJECT:raw_data:data) custom_obj;


-- Path 2
SELECT COUNT(*)
FROM BRONZE.CUSTOM_ACTIVITIES_RAW r,
LATERAL FLATTEN(
    INPUT => TRY_PARSE_JSON(
        REPLACE(r.JSON_OBJECT:raw_data:JSON_OBJECT::STRING, '''', '"')
    ):data
) custom_obj;


SELECT
    JSON_OBJECT,
    INSERT_DATE
FROM BRONZE.CUSTOM_ACTIVITIES_RAW
LIMIT 5;

SELECT
    TYPEOF(JSON_OBJECT) AS JSON_TYPE,
    OBJECT_KEYS(JSON_OBJECT) AS TOP_LEVEL_KEYS
FROM BRONZE.CUSTOM_ACTIVITIES_RAW
LIMIT 5;


