SELECT
    CUSTOM_ACTIVITY,
    STATUS_CHANGE,
    COUNT(*) AS TOTAL_RECORDS
FROM LEADS_ACTIVITIES_SUMMARY
WHERE CUSTOM_ACTIVITY = 'Triage Call'
GROUP BY
    CUSTOM_ACTIVITY,
    STATUS_CHANGE
ORDER BY TOTAL_RECORDS DESC;

SELECT
    CUSTOM_ACTIVITY,
    COUNT(*) AS TOTAL_RECORDS
FROM LEADS_ACTIVITIES_SUMMARY
GROUP BY CUSTOM_ACTIVITY
ORDER BY TOTAL_RECORDS DESC;

SELECT
    STATUS_CHANGE,
    COUNT(*) AS TOTAL_RECORDS
FROM LEADS_ACTIVITIES_SUMMARY
GROUP BY STATUS_CHANGE
ORDER BY TOTAL_RECORDS DESC;


SELECT DISTINCT
    CUSTOM_ACTIVITY
FROM LEADS_ACTIVITIES_SUMMARY
ORDER BY CUSTOM_ACTIVITY;


SELECT *
FROM LEADS_ACTIVITIES_SUMMARY
WHERE CUSTOM_ACTIVITY = '3) Triage Call'
LIMIT 20;

SELECT
    LEAD_ID,
    ACTIVITY_ID,
    CUSTOM_ACTIVITY,
    STATUS_CHANGE,
    TEXT,
    MEETING_STATUS,
    MEETING_STARTS_AT,
    MEETING_END_AT,
    CREATED_BY_NAME,
    ACTIVITY_AT
FROM LEADS_ACTIVITIES_SUMMARY
WHERE CUSTOM_ACTIVITY = '3) Triage Call'
LIMIT 50;


SELECT
    LEAD_ID,
    CUSTOM_ACTIVITY,
    ACTIVITY_AT
FROM LEADS_ACTIVITIES_SUMMARY
WHERE CUSTOM_ACTIVITY IN (
    '3) Triage Call',
    '5) Strategy Call',
    '7) New Sale'
)
ORDER BY
    LEAD_ID,
    ACTIVITY_AT;

    SELECT
    CUSTOM_ACTIVITY,
    CUSTOM_ACTIVITY_OUTCOME_NAME,
    COUNT(*) AS TOTAL
FROM LEADS_ACTIVITIES_SUMMARY
GROUP BY
    CUSTOM_ACTIVITY,
    CUSTOM_ACTIVITY_OUTCOME_NAME
ORDER BY
    CUSTOM_ACTIVITY,
    TOTAL DESC;

    SELECT
    CUSTOM_ACTIVITY,
    CUSTOM_ACTIVITY_OUTCOME_NAME,
    COUNT(*) AS TOTAL
FROM LEADS_ACTIVITIES_SUMMARY
GROUP BY
    CUSTOM_ACTIVITY,
    CUSTOM_ACTIVITY_OUTCOME_NAME
ORDER BY
    CUSTOM_ACTIVITY,
    TOTAL DESC;


    SELECT
    CUSTOM_ACTIVITY,
    STATUS_CHANGE,
    CUSTOM_ACTIVITY_OUTCOME_NAME,
    CUSTOM_ACTIVITY_OUTCOME,
    COUNT(*) AS TOTAL
FROM LEADS_ACTIVITIES_SUMMARY
WHERE CUSTOM_ACTIVITY IN ('3) Triage Call', '5) Strategy Call')
GROUP BY 1,2,3,4
ORDER BY CUSTOM_ACTIVITY, TOTAL DESC;


SELECT
    LEAD_ID,
    ACTIVITY_ID,
    CUSTOM_ACTIVITY,
    WRAPPED_ACTIVITIES
FROM LEADS_ACTIVITIES_SUMMARY
WHERE CUSTOM_ACTIVITY = '3) Triage Call'
LIMIT 5;