CREATE OR REPLACE TABLE SILVER.LEADS_ACTIVITIES_SUMMARY (
    ACTIVITY_ID STRING,
    LEAD_ID STRING,
    CONTACT_ID STRING,
    USER_ID STRING,
    TYPE STRING,
    TEXT STRING,
    STATUS_CHANGE STRING,
    CREATED_BY_NAME STRING,
    UPDATED_BY_NAME STRING,
    ATTENDEES VARIANT,
    CUSTOM_ACTIVITY_ID STRING,
    MEETING_STARTS_AT TIMESTAMP_NTZ,
    MEETING_END_AT TIMESTAMP_NTZ,
    MEETING_STATUS STRING,
    ACTIVITY_AT TIMESTAMP_NTZ,
    DATE_CREATED TIMESTAMP_NTZ,
    DATE_UPDATED TIMESTAMP_NTZ,
    CREATED_BY_USER STRING,
    UPDATED_BY_USER STRING,
    INSERT_DATE TIMESTAMP_NTZ,
    UPDATE_DATE TIMESTAMP_NTZ,
    WRAPPED_ACTIVITIES VARIANT,
    CUSTOM_ACTIVITY STRING,
    CUSTOM_ACTIVITY_OUTCOME_NAME STRING,
    CUSTOM_ACTIVITY_OUTCOME STRING,
    DEA_INTERNAL_NAME STRING,
    DEA_INTERNAL_EMAIL STRING
);

INSERT INTO SILVER.LEADS_ACTIVITIES_SUMMARY
SELECT
    lap.ACTIVITY_ID,
    lap.LEAD_ID,
    lap.CONTACT_ID,
    lap.USER_ID,
    lap.TYPE,
    lap.TEXT,
    lap.STATUS_CHANGE,
    lap.CREATED_BY_NAME,
    lap.UPDATED_BY_NAME,
    lap.ATTENDEES,
    lap.CUSTOM_ACTIVITY_ID,
    lap.MEETING_STARTS_AT,
    lap.MEETING_END_AT,
    lap.MEETING_STATUS,
    lap.ACTIVITY_AT,
    lap.DATE_CREATED,
    lap.DATE_UPDATED,
    lap.CREATED_BY_USER,
    lap.UPDATED_BY_USER,
    CURRENT_TIMESTAMP(),
    CURRENT_TIMESTAMP(),
    cad.WRAPPED_ACTIVITIES,
    ca.CUSTOM_ACTIVITY_NAME AS CUSTOM_ACTIVITY,
    ca.CUSTOM_ACTIVITY_OUTCOME_NAME,
    ca.CUSTOM_ACTIVITY_OUTCOME_ID AS CUSTOM_ACTIVITY_OUTCOME,
    cu.FIRST_NAME || ' ' || cu.LAST_NAME AS DEA_INTERNAL_NAME,
    cu.EMAIL AS DEA_INTERNAL_EMAIL
FROM SILVER.LEAD_ACTIVITIES_PROCESSED lap
LEFT JOIN SILVER.CUSTOM_ACTIVITIES_ALL_LEADS_DETAILS cad
    ON lap.ACTIVITY_ID = cad.ACTIVITY_ID
LEFT JOIN SILVER.CUSTOM_ACTIVITIES ca
    ON lap.CUSTOM_ACTIVITY_ID = ca.CUSTOM_ACTIVITY_ID
LEFT JOIN SILVER.CLOSE_CRM_USERS_PROCESSED cu
    ON lap.USER_ID = cu.USER_ID;

    SELECT COUNT(*)
FROM SILVER.LEADS_ACTIVITIES_SUMMARY;


SELECT *
FROM SILVER.LEADS_ACTIVITIES_SUMMARY
LIMIT 20;


-- 1. Base table count
SELECT COUNT(*)
FROM SILVER.LEAD_ACTIVITIES_PROCESSED;

--2. Distinct activity IDs

SELECT
    COUNT(*) AS ROWS,
    COUNT(DISTINCT ACTIVITY_ID) AS DISTINCT_ACTIVITY_IDS
FROM SILVER.CUSTOM_ACTIVITIES_ALL_LEADS_DETAILS;


--3. Check duplicate users

SELECT
    USER_ID,
    COUNT(*)
FROM SILVER.CLOSE_CRM_USERS_PROCESSED
GROUP BY USER_ID
HAVING COUNT(*) > 1;


--4. Check duplicate custom activities
SELECT
    CUSTOM_ACTIVITY_ID,
    COUNT(*)
FROM SILVER.CUSTOM_ACTIVITIES
GROUP BY CUSTOM_ACTIVITY_ID
HAVING COUNT(*) > 1;



SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT(DISTINCT ACTIVITY_ID) AS DISTINCT_ACTIVITY_IDS
FROM SILVER.CUSTOM_ACTIVITIES_ALL_LEADS_DETAILS;


TRUNCATE TABLE SILVER.LEADS_ACTIVITIES_SUMMARY;

INSERT INTO SILVER.LEADS_ACTIVITIES_SUMMARY
WITH CAD_DEDUP AS (
    SELECT *
    FROM SILVER.CUSTOM_ACTIVITIES_ALL_LEADS_DETAILS
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY ACTIVITY_ID
        ORDER BY UPDATE_DATE DESC, INSERT_DATE DESC
    ) = 1
)
SELECT
    lap.ACTIVITY_ID,
    lap.LEAD_ID,
    lap.CONTACT_ID,
    lap.USER_ID,
    lap.TYPE,
    lap.TEXT,
    lap.STATUS_CHANGE,
    lap.CREATED_BY_NAME,
    lap.UPDATED_BY_NAME,
    lap.ATTENDEES,
    lap.CUSTOM_ACTIVITY_ID,
    lap.MEETING_STARTS_AT,
    lap.MEETING_END_AT,
    lap.MEETING_STATUS,
    lap.ACTIVITY_AT,
    lap.DATE_CREATED,
    lap.DATE_UPDATED,
    lap.CREATED_BY_USER,
    lap.UPDATED_BY_USER,
    CURRENT_TIMESTAMP(),
    CURRENT_TIMESTAMP(),
    cad.WRAPPED_ACTIVITIES,
    ca.CUSTOM_ACTIVITY_NAME AS CUSTOM_ACTIVITY,
    ca.CUSTOM_ACTIVITY_OUTCOME_NAME,
    ca.CUSTOM_ACTIVITY_OUTCOME_ID AS CUSTOM_ACTIVITY_OUTCOME,
    cu.FIRST_NAME || ' ' || cu.LAST_NAME AS DEA_INTERNAL_NAME,
    cu.EMAIL AS DEA_INTERNAL_EMAIL
FROM SILVER.LEAD_ACTIVITIES_PROCESSED lap
LEFT JOIN CAD_DEDUP cad
    ON lap.ACTIVITY_ID = cad.ACTIVITY_ID
LEFT JOIN SILVER.CUSTOM_ACTIVITIES ca
    ON lap.CUSTOM_ACTIVITY_ID = ca.CUSTOM_ACTIVITY_ID
LEFT JOIN SILVER.CLOSE_CRM_USERS_PROCESSED cu
    ON lap.USER_ID = cu.USER_ID;


    TRUNCATE TABLE SILVER.LEADS_ACTIVITIES_SUMMARY;


INSERT INTO SILVER.LEADS_ACTIVITIES_SUMMARY
WITH CAD_DEDUP AS (
    SELECT *
    FROM SILVER.CUSTOM_ACTIVITIES_ALL_LEADS_DETAILS
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY ACTIVITY_ID
        ORDER BY UPDATE_DATE DESC, INSERT_DATE DESC
    ) = 1
),

BRONZE_CUSTOM_FIELDS AS (
    SELECT
        activity.value:id::STRING AS ACTIVITY_ID,
        activity.value:lead_id::STRING AS LEAD_ID,

        activity.value:"custom.cf_h3tYb9J6yPK7J4PMExDGsEqPCf8kBGBrRNIur2Dm5aN"::STRING AS TRIAGE_CALL_OUTCOME,
        activity.value:"custom.cf_dhJR4N7Rm6czuJthYGJP6KqUcuOzi7fqApGI7puWnMo"::STRING AS STRATEGY_CALL_OUTCOME

    FROM SALES_ANALYTICS_DB.BRONZE.LEAD_ACTIVITIES_RAW r,
    LATERAL FLATTEN(INPUT => r.JSON_OBJECT:raw_data:data) activity

    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY activity.value:lead_id::STRING, activity.value:id::STRING
        ORDER BY activity.value:activity_at::TIMESTAMP_NTZ DESC,
                 activity.value:date_updated::TIMESTAMP_NTZ DESC
    ) = 1
)

SELECT
    lap.ACTIVITY_ID,
    lap.LEAD_ID,
    lap.CONTACT_ID,
    lap.USER_ID,
    lap.TYPE,
    lap.TEXT,
    lap.STATUS_CHANGE,
    lap.CREATED_BY_NAME,
    lap.UPDATED_BY_NAME,
    lap.ATTENDEES,
    lap.CUSTOM_ACTIVITY_ID,
    lap.MEETING_STARTS_AT,
    lap.MEETING_END_AT,
    lap.MEETING_STATUS,
    lap.ACTIVITY_AT,
    lap.DATE_CREATED,
    lap.DATE_UPDATED,
    lap.CREATED_BY_USER,
    lap.UPDATED_BY_USER,
    CURRENT_TIMESTAMP(),
    CURRENT_TIMESTAMP(),
    cad.WRAPPED_ACTIVITIES,
    ca.CUSTOM_ACTIVITY_NAME AS CUSTOM_ACTIVITY,

    CASE
        WHEN ca.CUSTOM_ACTIVITY_NAME = '3) Triage Call' THEN 'Triage Call Outcome'
        WHEN ca.CUSTOM_ACTIVITY_NAME = '5) Strategy Call' THEN 'Strategy Call Outcome'
        ELSE ca.CUSTOM_ACTIVITY_OUTCOME_NAME
    END AS CUSTOM_ACTIVITY_OUTCOME_NAME,

    CASE
        WHEN ca.CUSTOM_ACTIVITY_NAME = '3) Triage Call' THEN bcf.TRIAGE_CALL_OUTCOME
        WHEN ca.CUSTOM_ACTIVITY_NAME = '5) Strategy Call' THEN bcf.STRATEGY_CALL_OUTCOME
        ELSE ca.CUSTOM_ACTIVITY_OUTCOME_ID
    END AS CUSTOM_ACTIVITY_OUTCOME,

    cu.FIRST_NAME || ' ' || cu.LAST_NAME AS DEA_INTERNAL_NAME,
    cu.EMAIL AS DEA_INTERNAL_EMAIL

FROM SILVER.LEAD_ACTIVITIES_PROCESSED lap
LEFT JOIN CAD_DEDUP cad
    ON lap.ACTIVITY_ID = cad.ACTIVITY_ID
LEFT JOIN BRONZE_CUSTOM_FIELDS bcf
    ON lap.ACTIVITY_ID = bcf.ACTIVITY_ID
   AND lap.LEAD_ID = bcf.LEAD_ID
LEFT JOIN SILVER.CUSTOM_ACTIVITIES ca
    ON lap.CUSTOM_ACTIVITY_ID = ca.CUSTOM_ACTIVITY_ID
LEFT JOIN SILVER.CLOSE_CRM_USERS_PROCESSED cu
    ON lap.USER_ID = cu.USER_ID;

    SELECT
    CUSTOM_ACTIVITY,
    CUSTOM_ACTIVITY_OUTCOME_NAME,
    CUSTOM_ACTIVITY_OUTCOME,
    COUNT(*) AS TOTAL
FROM SILVER.LEADS_ACTIVITIES_SUMMARY
WHERE CUSTOM_ACTIVITY IN ('3) Triage Call', '5) Strategy Call')
GROUP BY 1,2,3
ORDER BY CUSTOM_ACTIVITY, TOTAL DESC;


USE DATABASE SALES_ANALYTICS_DB;
USE SCHEMA SILVER;

ALTER TABLE LEADS_ACTIVITIES_SUMMARY ADD COLUMN IF NOT EXISTS SETTER_USER_ID STRING;
ALTER TABLE LEADS_ACTIVITIES_SUMMARY ADD COLUMN IF NOT EXISTS SETTER_EMAIL STRING;
ALTER TABLE LEADS_ACTIVITIES_SUMMARY ADD COLUMN IF NOT EXISTS SETTER_NAME STRING;

ALTER TABLE LEADS_ACTIVITIES_SUMMARY ADD COLUMN IF NOT EXISTS CLOSER_USER_ID STRING;
ALTER TABLE LEADS_ACTIVITIES_SUMMARY ADD COLUMN IF NOT EXISTS CLOSER_EMAIL STRING;
ALTER TABLE LEADS_ACTIVITIES_SUMMARY ADD COLUMN IF NOT EXISTS CLOSER_NAME STRING;

ALTER TABLE LEADS_ACTIVITIES_SUMMARY ADD COLUMN IF NOT EXISTS OFFER_PRESENTED STRING;
ALTER TABLE LEADS_ACTIVITIES_SUMMARY ADD COLUMN IF NOT EXISTS PROGRAM STRING;
ALTER TABLE LEADS_ACTIVITIES_SUMMARY ADD COLUMN IF NOT EXISTS CONTRACT_VALUE STRING;
ALTER TABLE LEADS_ACTIVITIES_SUMMARY ADD COLUMN IF NOT EXISTS CASH_COLLECTED STRING;
ALTER TABLE LEADS_ACTIVITIES_SUMMARY ADD COLUMN IF NOT EXISTS OBJECTIONS_FACED STRING;

``````````````````````````

TRUNCATE TABLE SILVER.LEADS_ACTIVITIES_SUMMARY;

INSERT INTO SILVER.LEADS_ACTIVITIES_SUMMARY
WITH CAD_DEDUP AS (
    SELECT *
    FROM SILVER.CUSTOM_ACTIVITIES_ALL_LEADS_DETAILS
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY ACTIVITY_ID
        ORDER BY UPDATE_DATE DESC, INSERT_DATE DESC
    ) = 1
),

BRONZE_CUSTOM_FIELDS AS (
    SELECT
        activity.value:id::STRING AS ACTIVITY_ID,
        activity.value:lead_id::STRING AS LEAD_ID,

        activity.value:"custom.cf_h3tYb9J6yPK7J4PMExDGsEqPCf8kBGBrRNIur2Dm5aN"::STRING AS TRIAGE_CALL_OUTCOME,
        activity.value:"custom.cf_dhJR4N7Rm6czuJthYGJP6KqUcuOzi7fqApGI7puWnMo"::STRING AS STRATEGY_CALL_OUTCOME,

        activity.value:"custom.cf_LGyzSTMPy37y87rDOUmFXlZA42HPSIpbipeT2OsQNHW"::STRING AS OFFER_PRESENTED,
        activity.value:"custom.cf_mXqKxcmjnlEW223wM4lgb04XyYwDm0GJ9v99xWHPWO2"::STRING AS PROGRAM,
        activity.value:"custom.cf_vIanPjPEit6ssajmWkcprF2V1nO1itfes8hOSnjmhfT"::STRING AS CONTRACT_VALUE,
        activity.value:"custom.cf_eyLbGJm9DYY7cuJk2otnCxhUEzK9ayEARiE81xPG5uY"::STRING AS CASH_COLLECTED,
        activity.value:"custom.cf_aIN5Gtqq33tUCCBxFTW63FY6d3mofnKIfFqfWPkvNla"::STRING AS OBJECTIONS_FACED,

        activity.value:"custom.cf_v385AJ8HSgepKQ3rvqo4yOA3nn49eGqz39DOqojJG5M"::STRING AS SETTER_USER_ID,
        activity.value:"custom.cf_Lv5lSqLOZwLrNhe5M7kWx2mF8Ge2Z23aw5NUNhbXvVS"::STRING AS CLOSER_USER_ID

    FROM SALES_ANALYTICS_DB.BRONZE.LEAD_ACTIVITIES_RAW r,
    LATERAL FLATTEN(INPUT => r.JSON_OBJECT:raw_data:data) activity

    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY activity.value:lead_id::STRING, activity.value:id::STRING
        ORDER BY activity.value:activity_at::TIMESTAMP_NTZ DESC,
                 activity.value:date_updated::TIMESTAMP_NTZ DESC
    ) = 1
)

SELECT
    lap.ACTIVITY_ID,
    lap.LEAD_ID,
    lap.CONTACT_ID,
    lap.USER_ID,
    lap.TYPE,
    lap.TEXT,
    lap.STATUS_CHANGE,
    lap.CREATED_BY_NAME,
    lap.UPDATED_BY_NAME,
    lap.ATTENDEES,
    lap.CUSTOM_ACTIVITY_ID,
    lap.MEETING_STARTS_AT,
    lap.MEETING_END_AT,
    lap.MEETING_STATUS,
    lap.ACTIVITY_AT,
    lap.DATE_CREATED,
    lap.DATE_UPDATED,
    lap.CREATED_BY_USER,
    lap.UPDATED_BY_USER,
    CURRENT_TIMESTAMP(),
    CURRENT_TIMESTAMP(),
    cad.WRAPPED_ACTIVITIES,
    ca.CUSTOM_ACTIVITY_NAME AS CUSTOM_ACTIVITY,

    CASE
        WHEN ca.CUSTOM_ACTIVITY_NAME = '3) Triage Call' THEN 'Triage Call Outcome'
        WHEN ca.CUSTOM_ACTIVITY_NAME = '5) Strategy Call' THEN 'Strategy Call Outcome'
        ELSE ca.CUSTOM_ACTIVITY_OUTCOME_NAME
    END AS CUSTOM_ACTIVITY_OUTCOME_NAME,

    CASE
        WHEN ca.CUSTOM_ACTIVITY_NAME = '3) Triage Call' THEN bcf.TRIAGE_CALL_OUTCOME
        WHEN ca.CUSTOM_ACTIVITY_NAME = '5) Strategy Call' THEN bcf.STRATEGY_CALL_OUTCOME
        ELSE ca.CUSTOM_ACTIVITY_OUTCOME_ID
    END AS CUSTOM_ACTIVITY_OUTCOME,

    cu.FIRST_NAME || ' ' || cu.LAST_NAME AS DEA_INTERNAL_NAME,
    cu.EMAIL AS DEA_INTERNAL_EMAIL,

    bcf.SETTER_USER_ID,
    su.EMAIL AS SETTER_EMAIL,
    su.FIRST_NAME || ' ' || su.LAST_NAME AS SETTER_NAME,

    bcf.CLOSER_USER_ID,
    clu.EMAIL AS CLOSER_EMAIL,
    clu.FIRST_NAME || ' ' || clu.LAST_NAME AS CLOSER_NAME,

    bcf.OFFER_PRESENTED,
    bcf.PROGRAM,
    bcf.CONTRACT_VALUE,
    bcf.CASH_COLLECTED,
    bcf.OBJECTIONS_FACED

FROM SILVER.LEAD_ACTIVITIES_PROCESSED lap
LEFT JOIN CAD_DEDUP cad
    ON lap.ACTIVITY_ID = cad.ACTIVITY_ID
LEFT JOIN BRONZE_CUSTOM_FIELDS bcf
    ON lap.ACTIVITY_ID = bcf.ACTIVITY_ID
   AND lap.LEAD_ID = bcf.LEAD_ID
LEFT JOIN SILVER.CUSTOM_ACTIVITIES ca
    ON lap.CUSTOM_ACTIVITY_ID = ca.CUSTOM_ACTIVITY_ID
LEFT JOIN SILVER.CLOSE_CRM_USERS_PROCESSED cu
    ON lap.USER_ID = cu.USER_ID
LEFT JOIN SILVER.CLOSE_CRM_USERS_PROCESSED su
    ON bcf.SETTER_USER_ID = su.USER_ID
LEFT JOIN SILVER.CLOSE_CRM_USERS_PROCESSED clu
    ON bcf.CLOSER_USER_ID = clu.USER_ID;


----

SELECT
    CUSTOM_ACTIVITY,
    COUNT_IF(SETTER_USER_ID IS NOT NULL) AS SETTER_ROWS,
    COUNT_IF(CLOSER_USER_ID IS NOT NULL) AS CLOSER_ROWS,
    COUNT_IF(OFFER_PRESENTED IS NOT NULL) AS OFFER_ROWS,
    COUNT_IF(CONTRACT_VALUE IS NOT NULL) AS CONTRACT_VALUE_ROWS,
    COUNT_IF(CASH_COLLECTED IS NOT NULL) AS CASH_COLLECTED_ROWS
FROM SILVER.LEADS_ACTIVITIES_SUMMARY
WHERE CUSTOM_ACTIVITY IN ('5) Strategy Call', '7) New Sale')
GROUP BY CUSTOM_ACTIVITY;


SELECT COUNT(*) 
FROM SILVER.LEADS_ACTIVITIES_SUMMARY;


UPDATE SALES_ANALYTICS_DB.SILVER.LEADS_ACTIVITIES_SUMMARY tgt

SET
    CUSTOM_ACTIVITY_OUTCOME_NAME = 'Prospecting Call Outcome',
    CUSTOM_ACTIVITY_OUTCOME = src.PROSPECTING_CALL_OUTCOME,
    UPDATE_DATE = CURRENT_TIMESTAMP()

FROM (
    SELECT
        activity.value:id::STRING AS ACTIVITY_ID,
        activity.value:lead_id::STRING AS LEAD_ID,

        activity.value:
            "custom.cf_Q2fsrD8VpPaunZLtyiy7P3vG6qJTv0w1ESmlhdHU2ra"
            ::STRING AS PROSPECTING_CALL_OUTCOME

    FROM SALES_ANALYTICS_DB.BRONZE.LEAD_ACTIVITIES_RAW r,
    LATERAL FLATTEN(
        INPUT => r.JSON_OBJECT:raw_data:data
    ) activity

    WHERE activity.value:
        "custom.cf_Q2fsrD8VpPaunZLtyiy7P3vG6qJTv0w1ESmlhdHU2ra"
        IS NOT NULL

    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY
            activity.value:lead_id::STRING,
            activity.value:id::STRING
        ORDER BY
            activity.value:activity_at::TIMESTAMP_NTZ DESC,
            activity.value:date_updated::TIMESTAMP_NTZ DESC,
            r.JSON_OBJECT:insert_date::TIMESTAMP_NTZ DESC
    ) = 1
) src

WHERE tgt.LEAD_ID = src.LEAD_ID
  AND tgt.ACTIVITY_ID = src.ACTIVITY_ID
  AND tgt.CUSTOM_ACTIVITY IN (
      '1) Prospecting Activity',
      '2) Prospecting Follow Up'
  );

  SELECT
    CUSTOM_ACTIVITY,
    CUSTOM_ACTIVITY_OUTCOME_NAME,
    CUSTOM_ACTIVITY_OUTCOME,
    COUNT(*) AS TOTAL_ROWS
FROM SALES_ANALYTICS_DB.SILVER.LEADS_ACTIVITIES_SUMMARY
WHERE CUSTOM_ACTIVITY IN (
    '1) Prospecting Activity',
    '2) Prospecting Follow Up'
)
GROUP BY
    CUSTOM_ACTIVITY,
    CUSTOM_ACTIVITY_OUTCOME_NAME,
    CUSTOM_ACTIVITY_OUTCOME
ORDER BY
    CUSTOM_ACTIVITY,
    TOTAL_ROWS DESC;


    ----
    SELECT
    CUSTOM_ACTIVITY,
    COUNT(*) AS STRATEGY_CALL_SCHEDULED_ROWS,
    COUNT(DISTINCT LEAD_ID) AS UNIQUE_LEADS
FROM SALES_ANALYTICS_DB.SILVER.LEADS_ACTIVITIES_SUMMARY
WHERE CUSTOM_ACTIVITY IN (
    '1) Prospecting Activity',
    '2) Prospecting Follow Up'
)
AND CUSTOM_ACTIVITY_OUTCOME = '2. Strategy Call Scheduled'
GROUP BY CUSTOM_ACTIVITY
ORDER BY CUSTOM_ACTIVITY;


SELECT COUNT(*) AS SUMMARY_ROWS
FROM SALES_ANALYTICS_DB.SILVER.LEADS_ACTIVITIES_SUMMARY;

SELECT
    LEAD_ID,
    ACTIVITY_ID,
    COUNT(*) AS CNT
FROM SALES_ANALYTICS_DB.SILVER.LEADS_ACTIVITIES_SUMMARY
GROUP BY
    LEAD_ID,
    ACTIVITY_ID
HAVING COUNT(*) > 1;