SELECT
    TYPE,
    COUNT(*) AS TOTAL
FROM SILVER.LEAD_ACTIVITIES_PROCESSED
GROUP BY TYPE
ORDER BY TOTAL DESC;

SELECT
    *
FROM SILVER.LEAD_ACTIVITIES_PROCESSED_TRANSIENT
WHERE JSON_OBJECT:_type::STRING = 'Email'
LIMIT 5;

CREATE OR REPLACE TABLE SILVER.LEAD_ACTIVITIES_EMAIL
(
    LEAD_ID STRING,
    ACTIVITY_AT TIMESTAMP_NTZ,
    ATTACHMENTS_JSON VARIANT,
    BODY_TEXT STRING,
    DATE_CREATED TIMESTAMP_NTZ,
    DATE_UPDATED TIMESTAMP_NTZ,
    DIRECTION STRING,
    ENVELOPE_JSON VARIANT,
    SENDER_JSON VARIANT,
    ACTIVITY_ID STRING,
    OPENS_JSON VARIANT,
    SENDER STRING,
    STATUS STRING,
    SUBJECT STRING,
    JSON_PAYLOAD VARIANT,
    USER_ID STRING,
    USER_NAME STRING,
    TEMPLATE_ID STRING,
    TEMPLATE_NAME STRING,
    DATE_SENT TIMESTAMP_NTZ,
    HAS_REPLY BOOLEAN,
    INSERT_DATE TIMESTAMP_NTZ
);

INSERT INTO SILVER.LEAD_ACTIVITIES_EMAIL
SELECT
    JSON_OBJECT:lead_id::STRING,
    JSON_OBJECT:activity_at::TIMESTAMP_NTZ,
    JSON_OBJECT:attachments,
    JSON_OBJECT:body_text::STRING,
    JSON_OBJECT:date_created::TIMESTAMP_NTZ,
    JSON_OBJECT:date_updated::TIMESTAMP_NTZ,
    JSON_OBJECT:direction::STRING,
    JSON_OBJECT:envelope,
    JSON_OBJECT:envelope:sender,
    JSON_OBJECT:id::STRING,
    JSON_OBJECT:opens,
    JSON_OBJECT:sender::STRING,
    JSON_OBJECT:status::STRING,
    JSON_OBJECT:subject::STRING,
    JSON_OBJECT,
    JSON_OBJECT:user_id::STRING,
    JSON_OBJECT:user_name::STRING,
    JSON_OBJECT:template_id::STRING,
    JSON_OBJECT:template_name::STRING,
    JSON_OBJECT:date_sent::TIMESTAMP_NTZ,
    JSON_OBJECT:has_reply::BOOLEAN,
    INSERT_DATE
FROM SILVER.LEAD_ACTIVITIES_PROCESSED_TRANSIENT
WHERE JSON_OBJECT:_type::STRING = 'Email';


SELECT COUNT(*)
FROM SILVER.LEAD_ACTIVITIES_EMAIL;

SELECT *
FROM SILVER.LEAD_ACTIVITIES_EMAIL
LIMIT 20;

SELECT COUNT(*)
FROM SILVER.LEAD_ACTIVITIES_PROCESSED_TRANSIENT
WHERE JSON_OBJECT:_type::STRING = 'Email';

TRUNCATE TABLE SILVER.LEAD_ACTIVITIES_EMAIL;


CREATE OR REPLACE TABLE SILVER.LEAD_ACTIVITIES_EMAIL (
    LEAD_ID STRING,
    ACTIVITY_AT TIMESTAMP_NTZ,
    ATTACHMENTS_JSON VARIANT,
    BODY_TEXT STRING,
    DATE_CREATED TIMESTAMP_NTZ,
    DATE_UPDATED TIMESTAMP_NTZ,
    DIRECTION STRING,
    ENVELOPE_JSON VARIANT,
    SENDER_JSON VARIANT,
    ACTIVITY_ID STRING,
    OPENS_JSON VARIANT,
    SENDER STRING,
    STATUS STRING,
    SUBJECT STRING,
    JSON_PAYLOAD VARIANT,
    USER_ID STRING,
    USER_NAME STRING,
    TEMPLATE_ID STRING,
    TEMPLATE_NAME STRING,
    DATE_SENT TIMESTAMP_NTZ,
    HAS_REPLY BOOLEAN,
    INSERT_DATE TIMESTAMP_NTZ,
    UPDATE_DATE TIMESTAMP_NTZ,
    MD5_HASH STRING
);


MERGE INTO SILVER.LEAD_ACTIVITIES_EMAIL tgt
USING (
    WITH email_flat AS (
        SELECT
            JSON_OBJECT:lead_id::STRING AS LEAD_ID,
            JSON_OBJECT:activity_at::TIMESTAMP_NTZ AS ACTIVITY_AT,
            JSON_OBJECT:attachments AS ATTACHMENTS_JSON,
            JSON_OBJECT:body_text::STRING AS BODY_TEXT,
            JSON_OBJECT:date_created::TIMESTAMP_NTZ AS DATE_CREATED,
            JSON_OBJECT:date_updated::TIMESTAMP_NTZ AS DATE_UPDATED,
            JSON_OBJECT:direction::STRING AS DIRECTION,
            JSON_OBJECT:envelope AS ENVELOPE_JSON,
            JSON_OBJECT:envelope:sender AS SENDER_JSON,
            JSON_OBJECT:id::STRING AS ACTIVITY_ID,
            JSON_OBJECT:opens AS OPENS_JSON,
            JSON_OBJECT:sender::STRING AS SENDER,
            JSON_OBJECT:status::STRING AS STATUS,
            JSON_OBJECT:subject::STRING AS SUBJECT,
            JSON_OBJECT AS JSON_PAYLOAD,
            JSON_OBJECT:user_id::STRING AS USER_ID,
            JSON_OBJECT:user_name::STRING AS USER_NAME,
            JSON_OBJECT:template_id::STRING AS TEMPLATE_ID,
            JSON_OBJECT:template_name::STRING AS TEMPLATE_NAME,
            JSON_OBJECT:date_sent::TIMESTAMP_NTZ AS DATE_SENT,
            JSON_OBJECT:has_reply::BOOLEAN AS HAS_REPLY,
            INSERT_DATE
        FROM SILVER.LEAD_ACTIVITIES_PROCESSED_TRANSIENT
        WHERE JSON_OBJECT:_type::STRING = 'Email'
    ),

    with_hash AS (
        SELECT
            *,
            MD5(
                COALESCE(LEAD_ID, '') || '|' ||
                COALESCE(ACTIVITY_ID, '') || '|' ||
                COALESCE(ACTIVITY_AT::STRING, '') || '|' ||
                COALESCE(DATE_UPDATED::STRING, '') || '|' ||
                COALESCE(STATUS, '') || '|' ||
                COALESCE(SUBJECT, '') || '|' ||
                COALESCE(BODY_TEXT, '') || '|' ||
                COALESCE(USER_ID, '')
            ) AS MD5_HASH
        FROM email_flat
    ),

    deduped AS (
        SELECT *
        FROM with_hash
        QUALIFY ROW_NUMBER() OVER (
            PARTITION BY LEAD_ID, ACTIVITY_ID
            ORDER BY ACTIVITY_AT DESC, DATE_UPDATED DESC, INSERT_DATE DESC
        ) = 1
    )

    SELECT * FROM deduped
) src
ON tgt.LEAD_ID = src.LEAD_ID
AND tgt.ACTIVITY_ID = src.ACTIVITY_ID

WHEN MATCHED AND tgt.MD5_HASH <> src.MD5_HASH THEN UPDATE SET
    tgt.ACTIVITY_AT = src.ACTIVITY_AT,
    tgt.ATTACHMENTS_JSON = src.ATTACHMENTS_JSON,
    tgt.BODY_TEXT = src.BODY_TEXT,
    tgt.DATE_CREATED = src.DATE_CREATED,
    tgt.DATE_UPDATED = src.DATE_UPDATED,
    tgt.DIRECTION = src.DIRECTION,
    tgt.ENVELOPE_JSON = src.ENVELOPE_JSON,
    tgt.SENDER_JSON = src.SENDER_JSON,
    tgt.OPENS_JSON = src.OPENS_JSON,
    tgt.SENDER = src.SENDER,
    tgt.STATUS = src.STATUS,
    tgt.SUBJECT = src.SUBJECT,
    tgt.JSON_PAYLOAD = src.JSON_PAYLOAD,
    tgt.USER_ID = src.USER_ID,
    tgt.USER_NAME = src.USER_NAME,
    tgt.TEMPLATE_ID = src.TEMPLATE_ID,
    tgt.TEMPLATE_NAME = src.TEMPLATE_NAME,
    tgt.DATE_SENT = src.DATE_SENT,
    tgt.HAS_REPLY = src.HAS_REPLY,
    tgt.UPDATE_DATE = CURRENT_TIMESTAMP(),
    tgt.MD5_HASH = src.MD5_HASH

WHEN NOT MATCHED THEN INSERT (
    LEAD_ID, ACTIVITY_AT, ATTACHMENTS_JSON, BODY_TEXT,
    DATE_CREATED, DATE_UPDATED, DIRECTION, ENVELOPE_JSON,
    SENDER_JSON, ACTIVITY_ID, OPENS_JSON, SENDER, STATUS,
    SUBJECT, JSON_PAYLOAD, USER_ID, USER_NAME, TEMPLATE_ID,
    TEMPLATE_NAME, DATE_SENT, HAS_REPLY, INSERT_DATE, UPDATE_DATE, MD5_HASH
)
VALUES (
    src.LEAD_ID, src.ACTIVITY_AT, src.ATTACHMENTS_JSON, src.BODY_TEXT,
    src.DATE_CREATED, src.DATE_UPDATED, src.DIRECTION, src.ENVELOPE_JSON,
    src.SENDER_JSON, src.ACTIVITY_ID, src.OPENS_JSON, src.SENDER, src.STATUS,
    src.SUBJECT, src.JSON_PAYLOAD, src.USER_ID, src.USER_NAME, src.TEMPLATE_ID,
    src.TEMPLATE_NAME, src.DATE_SENT, src.HAS_REPLY, src.INSERT_DATE, CURRENT_TIMESTAMP(), src.MD5_HASH
);

SELECT * FROM SILVER.LEAD_ACTIVITIES_EMAIL limit 20;

SELECT LEAD_ID, ACTIVITY_ID, COUNT(*) AS CNT
FROM SILVER.LEAD_ACTIVITIES_EMAIL
GROUP BY LEAD_ID, ACTIVITY_ID
HAVING COUNT(*) > 1;