USE DATABASE SALES_ANALYTICS_DB;
USE SCHEMA GOLD;

CREATE OR REPLACE VIEW GOLD.OUTBOUND_PROSPECT_DIALS AS
SELECT
    LEAD_ID,

    ACTIVITY_AT::DATE AS ACTIVITY_LOG_DATE,

    YEAR(ACTIVITY_AT) || '-' ||
    LPAD(WEEKISO(ACTIVITY_AT), 2, '0') AS PROSPECT_YEAR_WEEK,

    CUSTOM_ACTIVITY,

    -- CRM record lifecycle status, such as published or draft
    STATUS_CHANGE AS STATUS,

    CUSTOM_ACTIVITY_OUTCOME_NAME,
    CUSTOM_ACTIVITY_OUTCOME,

    DEA_INTERNAL_EMAIL AS SETTER_CLOSER_EMAIL,
    DEA_INTERNAL_NAME AS SETTER_CLOSER_NAME

FROM SALES_ANALYTICS_DB.SILVER.LEADS_ACTIVITIES_SUMMARY

WHERE CUSTOM_ACTIVITY IN (
    '1) Prospecting Activity',
    '2) Prospecting Follow Up'
);


SELECT COUNT(*) AS OUTBOUND_PROSPECT_DIALS_COUNT
FROM GOLD.OUTBOUND_PROSPECT_DIALS;

SELECT
    CUSTOM_ACTIVITY,
    COUNT(*) AS TOTAL_ROWS
FROM GOLD.OUTBOUND_PROSPECT_DIALS
GROUP BY CUSTOM_ACTIVITY
ORDER BY CUSTOM_ACTIVITY;

SELECT
    CUSTOM_ACTIVITY,
    CUSTOM_ACTIVITY_OUTCOME_NAME,
    CUSTOM_ACTIVITY_OUTCOME,
    COUNT(*) AS TOTAL_ROWS
FROM GOLD.OUTBOUND_PROSPECT_DIALS
GROUP BY
    CUSTOM_ACTIVITY,
    CUSTOM_ACTIVITY_OUTCOME_NAME,
    CUSTOM_ACTIVITY_OUTCOME
ORDER BY
    CUSTOM_ACTIVITY,
    TOTAL_ROWS DESC;

    SELECT
    COUNT(*) AS OUTBOUND_SET_ROWS,
    COUNT(DISTINCT LEAD_ID) AS OUTBOUND_SET_LEADS
FROM GOLD.OUTBOUND_PROSPECT_DIALS
WHERE CUSTOM_ACTIVITY_OUTCOME = '2. Strategy Call Scheduled';

SELECT
    (
        SELECT COUNT(*)
        FROM GOLD.OUTBOUND_PROSPECT_DIALS
        WHERE CUSTOM_ACTIVITY_OUTCOME = '2. Strategy Call Scheduled'
    ) AS DIAL_VIEW_BOOKED_ROWS,

    (
        SELECT COUNT(*)
        FROM GOLD.OUTBOUND_STRATEGIES_BOOKED
    ) AS BOOKED_VIEW_ROWS;


    SELECT
    COUNT(*) AS TOTAL_OUTBOUND_ACTIVITIES,
    COUNT(DISTINCT LEAD_ID) AS UNIQUE_LEADS_TOUCHED
FROM GOLD.OUTBOUND_PROSPECT_DIALS;


SELECT
    PROSPECT_YEAR_WEEK,
    COUNT(*) AS TOTAL_OUTBOUND_ACTIVITIES,
    COUNT(DISTINCT LEAD_ID) AS UNIQUE_LEADS_TOUCHED,
    COUNT_IF(
        CUSTOM_ACTIVITY_OUTCOME = '2. Strategy Call Scheduled'
    ) AS OUTBOUND_SETS
FROM GOLD.OUTBOUND_PROSPECT_DIALS
GROUP BY PROSPECT_YEAR_WEEK
ORDER BY PROSPECT_YEAR_WEEK;