SELECT
    CUSTOM_ACTIVITY,
    COUNT(*) AS TOTAL_ROWS
FROM SALES_ANALYTICS_DB.SILVER.LEADS_ACTIVITIES_SUMMARY
WHERE CUSTOM_ACTIVITY ILIKE '%prospect%'
   OR CUSTOM_ACTIVITY ILIKE '%outbound%'
GROUP BY CUSTOM_ACTIVITY
ORDER BY TOTAL_ROWS DESC;


SELECT
    CUSTOM_ACTIVITY,
    CUSTOM_ACTIVITY_OUTCOME_NAME,
    CUSTOM_ACTIVITY_OUTCOME,
    STATUS_CHANGE,
    COUNT(*) AS TOTAL_ROWS
FROM SALES_ANALYTICS_DB.SILVER.LEADS_ACTIVITIES_SUMMARY
WHERE CUSTOM_ACTIVITY ILIKE '%prospect%'
   OR CUSTOM_ACTIVITY ILIKE '%outbound%'
GROUP BY
    CUSTOM_ACTIVITY,
    CUSTOM_ACTIVITY_OUTCOME_NAME,
    CUSTOM_ACTIVITY_OUTCOME,
    STATUS_CHANGE
ORDER BY
    CUSTOM_ACTIVITY,
    TOTAL_ROWS DESC;

    SELECT
    CUSTOM_ACTIVITY,
    CUSTOM_ACTIVITY_OUTCOME_NAME,
    CUSTOM_ACTIVITY_OUTCOME,
    COUNT(*) AS TOTAL_ROWS
FROM SALES_ANALYTICS_DB.SILVER.LEADS_ACTIVITIES_SUMMARY
WHERE CUSTOM_ACTIVITY_OUTCOME = '2. Strategy Call Scheduled'
GROUP BY
    CUSTOM_ACTIVITY,
    CUSTOM_ACTIVITY_OUTCOME_NAME,
    CUSTOM_ACTIVITY_OUTCOME
ORDER BY TOTAL_ROWS DESC;

SELECT
    LEAD_ID,
    ACTIVITY_ID,
    CUSTOM_ACTIVITY,
    CUSTOM_ACTIVITY_OUTCOME_NAME,
    CUSTOM_ACTIVITY_OUTCOME,
    STATUS_CHANGE,
    ACTIVITY_AT,
    DEA_INTERNAL_EMAIL,
    DEA_INTERNAL_NAME,
    SETTER_EMAIL,
    SETTER_NAME
FROM SALES_ANALYTICS_DB.SILVER.LEADS_ACTIVITIES_SUMMARY
WHERE CUSTOM_ACTIVITY ILIKE '%prospect%'
   OR CUSTOM_ACTIVITY_OUTCOME = '2. Strategy Call Scheduled'
LIMIT 50;

SELECT
    CUSTOM_ACTIVITY,
    CUSTOM_ACTIVITY_OUTCOME_NAME,
    CUSTOM_ACTIVITY_OUTCOME,
    COUNT(*) AS TOTAL_ROWS
FROM SILVER.LEADS_ACTIVITIES_SUMMARY
WHERE CUSTOM_ACTIVITY IN (
    '1) Prospecting Activity',
    '2) Prospecting Follow Up'
)
  AND CUSTOM_ACTIVITY_OUTCOME IS NOT NULL
GROUP BY
    CUSTOM_ACTIVITY,
    CUSTOM_ACTIVITY_OUTCOME_NAME,
    CUSTOM_ACTIVITY_OUTCOME
ORDER BY
    TOTAL_ROWS DESC;

    SELECT
    LEAD_ID,
    ACTIVITY_ID,
    CUSTOM_ACTIVITY,
    TEXT,
    STATUS_CHANGE,
    WRAPPED_ACTIVITIES
FROM SILVER.LEADS_ACTIVITIES_SUMMARY
WHERE CUSTOM_ACTIVITY IN (
    '1) Prospecting Activity',
    '2) Prospecting Follow Up'
)
LIMIT 20;

SELECT
    DISTINCT CUSTOM_ACTIVITY,
    CUSTOM_ACTIVITY_OUTCOME_NAME,
    CUSTOM_ACTIVITY_OUTCOME
FROM SILVER.LEADS_ACTIVITIES_SUMMARY
WHERE CUSTOM_ACTIVITY IN (
    '1) Prospecting Activity',
    '2) Prospecting Follow Up'
);


USE DATABASE SALES_ANALYTICS_DB;
USE SCHEMA GOLD;

CREATE OR REPLACE VIEW GOLD.OUTBOUND_STRATEGIES_BOOKED AS
SELECT
    LEAD_ID,

    ACTIVITY_AT::DATE AS ACTIVITY_LOG_DATE,

    DEA_INTERNAL_EMAIL AS SETTER_CLOSER_EMAIL,
    DEA_INTERNAL_NAME AS SETTER_CLOSER_NAME,

    ACTIVITY_AT::DATE AS PROSPECT_CALL_DATE,

    1 AS STRATEGY_CALL_BOOKED,

    YEAR(ACTIVITY_AT) || '-' ||
    LPAD(WEEKISO(ACTIVITY_AT), 2, '0') AS SC_YEAR_WEEK

FROM SALES_ANALYTICS_DB.SILVER.LEADS_ACTIVITIES_SUMMARY

WHERE CUSTOM_ACTIVITY IN (
    '1) Prospecting Activity',
    '2) Prospecting Follow Up'
)
AND CUSTOM_ACTIVITY_OUTCOME = '2. Strategy Call Scheduled';


SELECT * 
FROM GOLD.OUTBOUND_STRATEGIES_BOOKED;

SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT(DISTINCT LEAD_ID) AS UNIQUE_LEADS
FROM GOLD.OUTBOUND_STRATEGIES_BOOKED;


SELECT
    CUSTOM_ACTIVITY,
    COUNT(*) AS SILVER_ROWS
FROM SALES_ANALYTICS_DB.SILVER.LEADS_ACTIVITIES_SUMMARY
WHERE CUSTOM_ACTIVITY IN (
    '1) Prospecting Activity',
    '2) Prospecting Follow Up'
)
AND CUSTOM_ACTIVITY_OUTCOME = '2. Strategy Call Scheduled'
GROUP BY CUSTOM_ACTIVITY
ORDER BY CUSTOM_ACTIVITY;


SELECT
    SC_YEAR_WEEK,
    COUNT(*) AS STRATEGIES_BOOKED
FROM GOLD.OUTBOUND_STRATEGIES_BOOKED
GROUP BY SC_YEAR_WEEK
ORDER BY SC_YEAR_WEEK;

SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT_IF(SETTER_CLOSER_EMAIL IS NOT NULL) AS EMAIL_ROWS,
    COUNT_IF(SETTER_CLOSER_NAME IS NOT NULL) AS NAME_ROWS
FROM GOLD.OUTBOUND_STRATEGIES_BOOKED;