SELECT
    JSON_OBJECT::STRING AS RAW_JSON
FROM SALES_ANALYTICS_DB.BRONZE.LEAD_ACTIVITIES_RAW
WHERE JSON_OBJECT::STRING ILIKE '%custom.%'
LIMIT 5;

SELECT
    JSON_OBJECT
FROM SALES_ANALYTICS_DB.BRONZE.CUSTOM_ACTIVITIES_RAW
WHERE JSON_OBJECT::STRING ILIKE '%cf_3JFRKeLpnUvmsOsVG478u5iAQZ5i5dPmvKbIkYLUaaH%'
LIMIT 1;

SELECT
    JSON_OBJECT
FROM SALES_ANALYTICS_DB.BRONZE.CUSTOM_ACTIVITIES_RAW
WHERE JSON_OBJECT::STRING ILIKE '%cf_7EQ4NbImGdxDOQNwHVneg8JIjZj7wxprE3tMGhtwDOD%'
LIMIT 1;


SELECT
    JSON_OBJECT::STRING
FROM SALES_ANALYTICS_DB.BRONZE.LEAD_ACTIVITIES_RAW
WHERE JSON_OBJECT::STRING ILIKE '%cf_h3tYb9J6yPK7J4PMExDGsEqPCf8kBGBrRNIur2Dm5aN%'
   OR JSON_OBJECT::STRING ILIKE '%cf_dhJR4N7Rm6czuJthYGJP6KqUcuOzi7fqApGI7puWnMo%'
   OR JSON_OBJECT::STRING ILIKE '%cf_LGyzSTMPy37y87rDOUmFXlZA42HPSIpbipeT2OsQNHW%'
   OR JSON_OBJECT::STRING ILIKE '%cf_vIanPjPEit6ssajmWkcprF2V1nO1itfes8hOSnjmhfT%'
   OR JSON_OBJECT::STRING ILIKE '%cf_eyLbGJm9DYY7cuJk2otnCxhUEzK9ayEARiE81xPG5uY%'
LIMIT 10;


SELECT
    ACTIVITY.VALUE:id::STRING AS ACTIVITY_ID,
    ACTIVITY.VALUE:lead_id::STRING AS LEAD_ID,
    ACTIVITY.VALUE:custom_activity_id::STRING AS CUSTOM_ACTIVITY_ID,

    ACTIVITY.VALUE:"custom.cf_h3tYb9J6yPK7J4PMExDGsEqPCf8kBGBrRNIur2Dm5aN"::STRING AS TRIAGE_CALL_OUTCOME,
    ACTIVITY.VALUE:"custom.cf_dhJR4N7Rm6czuJthYGJP6KqUcuOzi7fqApGI7puWnMo"::STRING AS STRATEGY_CALL_OUTCOME,
    ACTIVITY.VALUE:"custom.cf_LGyzSTMPy37y87rDOUmFXlZA42HPSIpbipeT2OsQNHW"::STRING AS OFFER_PRESENTED,
    ACTIVITY.VALUE:"custom.cf_vIanPjPEit6ssajmWkcprF2V1nO1itfes8hOSnjmhfT"::STRING AS CONTRACT_VALUE,
    ACTIVITY.VALUE:"custom.cf_eyLbGJm9DYY7cuJk2otnCxhUEzK9ayEARiE81xPG5uY"::STRING AS CASH_COLLECTED,
    ACTIVITY.VALUE:"custom.cf_v385AJ8HSgepKQ3rvqo4yOA3nn49eGqz39DOqojJG5M"::STRING AS SETTER_USER_ID,
    ACTIVITY.VALUE:"custom.cf_Lv5lSqLOZwLrNhe5M7kWx2mF8Ge2Z23aw5NUNhbXvVS"::STRING AS CLOSER_USER_ID,
    ACTIVITY.VALUE:"custom.cf_mXqKxcmjnlEW223wM4lgb04XyYwDm0GJ9v99xWHPWO2"::STRING AS PROGRAM,
    ACTIVITY.VALUE:"custom.cf_aIN5Gtqq33tUCCBxFTW63FY6d3mofnKIfFqfWPkvNla"::STRING AS OBJECTIONS_FACED

FROM SALES_ANALYTICS_DB.BRONZE.LEAD_ACTIVITIES_RAW R,
LATERAL FLATTEN(INPUT => R.JSON_OBJECT:raw_data:JSON_OBJECT:data) LEAD_OBJ,
LATERAL FLATTEN(INPUT => LEAD_OBJ.VALUE:activities) ACTIVITY

WHERE ACTIVITY.VALUE:type::STRING = 'CustomActivity'
LIMIT 100;

WITH CUSTOM_FIELD_TEST AS (
    SELECT
        ACTIVITY.VALUE:"custom.cf_h3tYb9J6yPK7J4PMExDGsEqPCf8kBGBrRNIur2Dm5aN"::STRING AS TRIAGE_CALL_OUTCOME,
        ACTIVITY.VALUE:"custom.cf_dhJR4N7Rm6czuJthYGJP6KqUcuOzi7fqApGI7puWnMo"::STRING AS STRATEGY_CALL_OUTCOME,
        ACTIVITY.VALUE:"custom.cf_LGyzSTMPy37y87rDOUmFXlZA42HPSIpbipeT2OsQNHW"::STRING AS OFFER_PRESENTED,
        ACTIVITY.VALUE:"custom.cf_vIanPjPEit6ssajmWkcprF2V1nO1itfes8hOSnjmhfT"::STRING AS CONTRACT_VALUE,
        ACTIVITY.VALUE:"custom.cf_eyLbGJm9DYY7cuJk2otnCxhUEzK9ayEARiE81xPG5uY"::STRING AS CASH_COLLECTED
    FROM SALES_ANALYTICS_DB.BRONZE.LEAD_ACTIVITIES_RAW R,
    LATERAL FLATTEN(INPUT => R.JSON_OBJECT:raw_data:JSON_OBJECT:data) LEAD_OBJ,
    LATERAL FLATTEN(INPUT => LEAD_OBJ.VALUE:activities) ACTIVITY
    WHERE ACTIVITY.VALUE:type::STRING = 'CustomActivity'
)

SELECT
    COUNT_IF(TRIAGE_CALL_OUTCOME IS NOT NULL) AS TRIAGE_OUTCOME_ROWS,
    COUNT_IF(STRATEGY_CALL_OUTCOME IS NOT NULL) AS STRATEGY_OUTCOME_ROWS,
    COUNT_IF(OFFER_PRESENTED IS NOT NULL) AS OFFER_PRESENTED_ROWS,
    COUNT_IF(CONTRACT_VALUE IS NOT NULL) AS CONTRACT_VALUE_ROWS,
    COUNT_IF(CASH_COLLECTED IS NOT NULL) AS CASH_COLLECTED_ROWS
FROM CUSTOM_FIELD_TEST;

SELECT
    ACTIVITY.VALUE
FROM SALES_ANALYTICS_DB.BRONZE.LEAD_ACTIVITIES_RAW R,
LATERAL FLATTEN(INPUT => R.JSON_OBJECT:raw_data:JSON_OBJECT:data) LEAD_OBJ,
LATERAL FLATTEN(INPUT => LEAD_OBJ.VALUE:activities) ACTIVITY
WHERE ACTIVITY.VALUE:type::STRING = 'CustomActivity'
LIMIT 1;


SELECT
    OBJECT_KEYS(ACTIVITY.VALUE) AS TOP_LEVEL_KEYS
FROM SALES_ANALYTICS_DB.BRONZE.LEAD_ACTIVITIES_RAW R,
LATERAL FLATTEN(INPUT => R.JSON_OBJECT:raw_data:JSON_OBJECT:data) LEAD_OBJ,
LATERAL FLATTEN(INPUT => LEAD_OBJ.VALUE:activities) ACTIVITY
WHERE ACTIVITY.VALUE:type::STRING = 'CustomActivity'
LIMIT 5;

SELECT
    OBJECT_KEYS(JSON_OBJECT) AS ROOT_KEYS,
    JSON_OBJECT
FROM SALES_ANALYTICS_DB.BRONZE.LEAD_ACTIVITIES_RAW
LIMIT 1;

SELECT
    JSON_OBJECT:raw_data AS RAW_DATA,
    TYPEOF(JSON_OBJECT:raw_data) AS RAW_DATA_TYPE,
    JSON_OBJECT:data AS DATA_FIELD,
    TYPEOF(JSON_OBJECT:data) AS DATA_FIELD_TYPE
FROM SALES_ANALYTICS_DB.BRONZE.LEAD_ACTIVITIES_RAW
LIMIT 5;

SELECT
    TYPEOF(JSON_OBJECT:raw_data) AS RAW_TYPE,
    TYPEOF(PARSE_JSON(JSON_OBJECT:raw_data)) AS PARSED_TYPE,
    TYPEOF(PARSE_JSON(JSON_OBJECT:raw_data):data) AS DATA_TYPE
FROM SALES_ANALYTICS_DB.BRONZE.LEAD_ACTIVITIES_RAW
LIMIT 5;


SELECT
    VALUE
FROM SALES_ANALYTICS_DB.BRONZE.LEAD_ACTIVITIES_RAW R,
LATERAL FLATTEN(
    INPUT => R.JSON_OBJECT:raw_data:data
)
LIMIT 1;

SELECT
    OBJECT_KEYS(VALUE)
FROM SALES_ANALYTICS_DB.BRONZE.LEAD_ACTIVITIES_RAW R,
LATERAL FLATTEN(
    INPUT => R.JSON_OBJECT:raw_data:data
)
LIMIT 5;

SELECT
    ACTIVITY.VALUE:id::STRING AS ACTIVITY_ID,
    ACTIVITY.VALUE:lead_id::STRING AS LEAD_ID,
    ACTIVITY.VALUE:_type::STRING AS ACTIVITY_TYPE,
    ACTIVITY.VALUE:custom_activity_type_id::STRING AS CUSTOM_ACTIVITY_ID,
    ACTIVITY.VALUE
FROM SALES_ANALYTICS_DB.BRONZE.LEAD_ACTIVITIES_RAW R,
LATERAL FLATTEN(INPUT => R.JSON_OBJECT:raw_data:data) ACTIVITY
WHERE ACTIVITY.VALUE:_type::STRING = 'CustomActivity'
LIMIT 10;

SELECT
    ACTIVITY.VALUE:id::STRING AS ACTIVITY_ID,
    ACTIVITY.VALUE:lead_id::STRING AS LEAD_ID,
    ACTIVITY.VALUE:custom_activity_type_id::STRING AS CUSTOM_ACTIVITY_ID,

    ACTIVITY.VALUE:"custom.cf_h3tYb9J6yPK7J4PMExDGsEqPCf8kBGBrRNIur2Dm5aN"::STRING AS TRIAGE_CALL_OUTCOME,
    ACTIVITY.VALUE:"custom.cf_dhJR4N7Rm6czuJthYGJP6KqUcuOzi7fqApGI7puWnMo"::STRING AS STRATEGY_CALL_OUTCOME,
    ACTIVITY.VALUE:"custom.cf_LGyzSTMPy37y87rDOUmFXlZA42HPSIpbipeT2OsQNHW"::STRING AS OFFER_PRESENTED,
    ACTIVITY.VALUE:"custom.cf_vIanPjPEit6ssajmWkcprF2V1nO1itfes8hOSnjmhfT"::STRING AS CONTRACT_VALUE,
    ACTIVITY.VALUE:"custom.cf_eyLbGJm9DYY7cuJk2otnCxhUEzK9ayEARiE81xPG5uY"::STRING AS CASH_COLLECTED,
    ACTIVITY.VALUE:"custom.cf_v385AJ8HSgepKQ3rvqo4yOA3nn49eGqz39DOqojJG5M"::STRING AS SETTER_USER_ID,
    ACTIVITY.VALUE:"custom.cf_Lv5lSqLOZwLrNhe5M7kWx2mF8Ge2Z23aw5NUNhbXvVS"::STRING AS CLOSER_USER_ID,
    ACTIVITY.VALUE:"custom.cf_mXqKxcmjnlEW223wM4lgb04XyYwDm0GJ9v99xWHPWO2"::STRING AS PROGRAM,
    ACTIVITY.VALUE:"custom.cf_aIN5Gtqq33tUCCBxFTW63FY6d3mofnKIfFqfWPkvNla"::STRING AS OBJECTIONS_FACED

FROM SALES_ANALYTICS_DB.BRONZE.LEAD_ACTIVITIES_RAW R,
LATERAL FLATTEN(INPUT => R.JSON_OBJECT:raw_data:data) ACTIVITY
WHERE ACTIVITY.VALUE:_type::STRING = 'CustomActivity'
LIMIT 100;


-- 1. Confirm row count did not change
SELECT COUNT(*) AS SUMMARY_ROWS
FROM SILVER.LEADS_ACTIVITIES_SUMMARY;

-- got 1063628

-- 2. Confirm no duplicate lead/activity pairs
SELECT
    LEAD_ID,
    ACTIVITY_ID,
    COUNT(*) AS CNT
FROM SILVER.LEADS_ACTIVITIES_SUMMARY
GROUP BY LEAD_ID, ACTIVITY_ID
HAVING COUNT(*) > 1;

--  got 0

-- 3. Confirm Triage outcomes are populated
SELECT
    CUSTOM_ACTIVITY_OUTCOME,
    COUNT(*) AS TOTAL
FROM SILVER.LEADS_ACTIVITIES_SUMMARY
WHERE CUSTOM_ACTIVITY = '3) Triage Call'
GROUP BY CUSTOM_ACTIVITY_OUTCOME
ORDER BY TOTAL DESC;

-- 4. Confirm Strategy outcomes are populated
SELECT
    CUSTOM_ACTIVITY_OUTCOME,
    COUNT(*) AS TOTAL
FROM SILVER.LEADS_ACTIVITIES_SUMMARY
WHERE CUSTOM_ACTIVITY = '5) Strategy Call'
GROUP BY CUSTOM_ACTIVITY_OUTCOME
ORDER BY TOTAL DESC;