SHOW INTEGRATIONS;
SHOW STAGES;

LIST @SALES_ANALYTICS_S3_STAGE;

USE DATABASE SALES_ANALYTICS_DB;

CREATE OR REPLACE FILE FORMAT PUBLIC.BACKUP_PARQUET_FORMAT
    TYPE = PARQUET
    COMPRESSION = SNAPPY;

    CREATE OR REPLACE FILE FORMAT PUBLIC.BACKUP_CSV_FORMAT
    TYPE = CSV
    FIELD_DELIMITER = ','
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('NULL')
    EMPTY_FIELD_AS_NULL = FALSE
    COMPRESSION = GZIP;

    COPY INTO @SALES_ANALYTICS_S3_STAGE/snowflake_backup/bronze/custom_activities_raw/
FROM (
    SELECT *
    FROM SALES_ANALYTICS_DB.BRONZE.CUSTOM_ACTIVITIES_RAW
)
FILE_FORMAT = (
    FORMAT_NAME = SALES_ANALYTICS_DB.PUBLIC.BACKUP_PARQUET_FORMAT
)
HEADER = TRUE
OVERWRITE = TRUE;

DESC INTEGRATION SALES_ANALYTICS_S3_INT;

SHOW STAGES LIKE 'SALES_ANALYTICS_BACKUP_STAGE'
IN SCHEMA SALES_ANALYTICS_DB.PUBLIC;

USE DATABASE SALES_ANALYTICS_DB;
USE SCHEMA PUBLIC;

CREATE OR REPLACE STAGE SALES_ANALYTICS_BACKUP_STAGE
    URL = 's3://sales-analytics-raw-aqib-test/snowflake_backup/'
    STORAGE_INTEGRATION = SALES_ANALYTICS_S3_INT;

    LIST @SALES_ANALYTICS_DB.PUBLIC.SALES_ANALYTICS_BACKUP_STAGE;

    USE DATABASE SALES_ANALYTICS_DB;
USE SCHEMA PUBLIC;

CREATE OR REPLACE STAGE SALES_ANALYTICS_BACKUP_STAGE
    URL = 's3://sales-analytics-raw-aqib-test/snowflake_backup/'
    STORAGE_INTEGRATION = SALES_ANALYTICS_S3_INT;


    CREATE OR REPLACE FILE FORMAT
    SALES_ANALYTICS_DB.PUBLIC.BACKUP_CSV_FORMAT
TYPE = CSV
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
COMPRESSION = GZIP;

COPY INTO
    @SALES_ANALYTICS_DB.PUBLIC.SALES_ANALYTICS_BACKUP_STAGE/test/
FROM (
    SELECT *
    FROM SALES_ANALYTICS_DB.GOLD.CLOSER_REPORT
    LIMIT 10
)
FILE_FORMAT = (
    FORMAT_NAME = SALES_ANALYTICS_DB.PUBLIC.BACKUP_CSV_FORMAT
)
HEADER = TRUE
SINGLE = TRUE
OVERWRITE = TRUE;

LIST @SALES_ANALYTICS_DB.PUBLIC.SALES_ANALYTICS_BACKUP_STAGE/test/;

COPY INTO
    @SALES_ANALYTICS_DB.PUBLIC.SALES_ANALYTICS_BACKUP_STAGE/test/
FROM (
    SELECT *
    FROM SALES_ANALYTICS_DB.GOLD.CLOSER_REPORT
    LIMIT 10
)
FILE_FORMAT = (
    FORMAT_NAME = SALES_ANALYTICS_DB.PUBLIC.BACKUP_CSV_FORMAT
)
HEADER = TRUE
SINGLE = TRUE
OVERWRITE = TRUE;

COPY INTO @SALES_ANALYTICS_S3_STAGE/snowflake_backup/bronze/custom_activities_raw/
FROM (
    SELECT *
    FROM SALES_ANALYTICS_DB.BRONZE.CUSTOM_ACTIVITIES_RAW
)
FILE_FORMAT = (
    FORMAT_NAME = SALES_ANALYTICS_DB.PUBLIC.BACKUP_PARQUET_FORMAT
)
HEADER = TRUE
OVERWRITE = TRUE;SALES_ANALYTICS_DB.EXPORTS