USE DATABASE SALES_ANALYTICS_DB;
USE SCHEMA PUBLIC;

CREATE OR REPLACE FILE FORMAT BACKUP_PARQUET_FORMAT
    TYPE = PARQUET
    COMPRESSION = SNAPPY;

CREATE OR REPLACE FILE FORMAT BACKUP_CSV_FORMAT
    TYPE = CSV
    FIELD_DELIMITER = ','
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('NULL')
    EMPTY_FIELD_AS_NULL = FALSE
    COMPRESSION = GZIP;


    -- ============================================================
-- BRONZE BACKUP
-- ============================================================

COPY INTO
    @SALES_ANALYTICS_DB.PUBLIC.SALES_ANALYTICS_BACKUP_STAGE/bronze/close_crm_users_raw/
FROM (
    SELECT *
    FROM SALES_ANALYTICS_DB.BRONZE.CLOSE_CRM_USERS_RAW
)
FILE_FORMAT = (
    FORMAT_NAME = SALES_ANALYTICS_DB.PUBLIC.BACKUP_PARQUET_FORMAT
)
HEADER = TRUE
OVERWRITE = TRUE;


COPY INTO
    @SALES_ANALYTICS_DB.PUBLIC.SALES_ANALYTICS_BACKUP_STAGE/bronze/custom_activities_raw/
FROM (
    SELECT *
    FROM SALES_ANALYTICS_DB.BRONZE.CUSTOM_ACTIVITIES_RAW
)
FILE_FORMAT = (
    FORMAT_NAME = SALES_ANALYTICS_DB.PUBLIC.BACKUP_PARQUET_FORMAT
)
HEADER = TRUE
OVERWRITE = TRUE;


COPY INTO
    @SALES_ANALYTICS_DB.PUBLIC.SALES_ANALYTICS_BACKUP_STAGE/bronze/leads_raw/
FROM (
    SELECT *
    FROM SALES_ANALYTICS_DB.BRONZE.LEADS_RAW
)
FILE_FORMAT = (
    FORMAT_NAME = SALES_ANALYTICS_DB.PUBLIC.BACKUP_PARQUET_FORMAT
)
HEADER = TRUE
OVERWRITE = TRUE;


COPY INTO
    @SALES_ANALYTICS_DB.PUBLIC.SALES_ANALYTICS_BACKUP_STAGE/bronze/lead_activities_raw/
FROM (
    SELECT *
    FROM SALES_ANALYTICS_DB.BRONZE.LEAD_ACTIVITIES_RAW
)
FILE_FORMAT = (
    FORMAT_NAME = SALES_ANALYTICS_DB.PUBLIC.BACKUP_PARQUET_FORMAT
)
HEADER = TRUE
OVERWRITE = TRUE;

-- ============================================================
-- SILVER BACKUP
-- ============================================================

COPY INTO
    @SALES_ANALYTICS_DB.PUBLIC.SALES_ANALYTICS_BACKUP_STAGE/silver/close_crm_users_processed/
FROM (
    SELECT *
    FROM SALES_ANALYTICS_DB.SILVER.CLOSE_CRM_USERS_PROCESSED
)
FILE_FORMAT = (
    FORMAT_NAME = SALES_ANALYTICS_DB.PUBLIC.BACKUP_PARQUET_FORMAT
)
HEADER = TRUE
OVERWRITE = TRUE;


COPY INTO
    @SALES_ANALYTICS_DB.PUBLIC.SALES_ANALYTICS_BACKUP_STAGE/silver/custom_activities/
FROM (
    SELECT *
    FROM SALES_ANALYTICS_DB.SILVER.CUSTOM_ACTIVITIES
)
FILE_FORMAT = (
    FORMAT_NAME = SALES_ANALYTICS_DB.PUBLIC.BACKUP_PARQUET_FORMAT
)
HEADER = TRUE
OVERWRITE = TRUE;


COPY INTO
    @SALES_ANALYTICS_DB.PUBLIC.SALES_ANALYTICS_BACKUP_STAGE/silver/custom_activities_all_leads_details/
FROM (
    SELECT *
    FROM SALES_ANALYTICS_DB.SILVER.CUSTOM_ACTIVITIES_ALL_LEADS_DETAILS
)
FILE_FORMAT = (
    FORMAT_NAME = SALES_ANALYTICS_DB.PUBLIC.BACKUP_PARQUET_FORMAT
)
HEADER = TRUE
OVERWRITE = TRUE;


COPY INTO
    @SALES_ANALYTICS_DB.PUBLIC.SALES_ANALYTICS_BACKUP_STAGE/silver/custom_activities_transient/
FROM (
    SELECT *
    FROM SALES_ANALYTICS_DB.SILVER.CUSTOM_ACTIVITIES_TRANSIENT
)
FILE_FORMAT = (
    FORMAT_NAME = SALES_ANALYTICS_DB.PUBLIC.BACKUP_PARQUET_FORMAT
)
HEADER = TRUE
OVERWRITE = TRUE;


COPY INTO
    @SALES_ANALYTICS_DB.PUBLIC.SALES_ANALYTICS_BACKUP_STAGE/silver/leads_activities_summary/
FROM (
    SELECT *
    FROM SALES_ANALYTICS_DB.SILVER.LEADS_ACTIVITIES_SUMMARY
)
FILE_FORMAT = (
    FORMAT_NAME = SALES_ANALYTICS_DB.PUBLIC.BACKUP_PARQUET_FORMAT
)
HEADER = TRUE
OVERWRITE = TRUE;


COPY INTO
    @SALES_ANALYTICS_DB.PUBLIC.SALES_ANALYTICS_BACKUP_STAGE/silver/leads_activities_summary_transient/
FROM (
    SELECT *
    FROM SALES_ANALYTICS_DB.SILVER.LEADS_ACTIVITIES_SUMMARY_TRANSIENT
)
FILE_FORMAT = (
    FORMAT_NAME = SALES_ANALYTICS_DB.PUBLIC.BACKUP_PARQUET_FORMAT
)
HEADER = TRUE
OVERWRITE = TRUE;


COPY INTO
    @SALES_ANALYTICS_DB.PUBLIC.SALES_ANALYTICS_BACKUP_STAGE/silver/lead_activities_email/
FROM (
    SELECT *
    FROM SALES_ANALYTICS_DB.SILVER.LEAD_ACTIVITIES_EMAIL
)
FILE_FORMAT = (
    FORMAT_NAME = SALES_ANALYTICS_DB.PUBLIC.BACKUP_PARQUET_FORMAT
)
HEADER = TRUE
OVERWRITE = TRUE;


COPY INTO
    @SALES_ANALYTICS_DB.PUBLIC.SALES_ANALYTICS_BACKUP_STAGE/silver/lead_activities_processed/
FROM (
    SELECT *
    FROM SALES_ANALYTICS_DB.SILVER.LEAD_ACTIVITIES_PROCESSED
)
FILE_FORMAT = (
    FORMAT_NAME = SALES_ANALYTICS_DB.PUBLIC.BACKUP_PARQUET_FORMAT
)
HEADER = TRUE
OVERWRITE = TRUE;


COPY INTO
    @SALES_ANALYTICS_DB.PUBLIC.SALES_ANALYTICS_BACKUP_STAGE/silver/lead_activities_processed_transient/
FROM (
    SELECT *
    FROM SALES_ANALYTICS_DB.SILVER.LEAD_ACTIVITIES_PROCESSED_TRANSIENT
)
FILE_FORMAT = (
    FORMAT_NAME = SALES_ANALYTICS_DB.PUBLIC.BACKUP_PARQUET_FORMAT
)
HEADER = TRUE
OVERWRITE = TRUE;

-- ============================================================
-- GOLD BUSINESS VIEW BACKUP
-- ============================================================

COPY INTO
    @SALES_ANALYTICS_DB.PUBLIC.SALES_ANALYTICS_BACKUP_STAGE/gold/all_strategies_details/
FROM (
    SELECT *
    FROM SALES_ANALYTICS_DB.GOLD.ALL_STRATEGIES_DETAILS
)
FILE_FORMAT = (
    FORMAT_NAME = SALES_ANALYTICS_DB.PUBLIC.BACKUP_CSV_FORMAT
)
HEADER = TRUE
OVERWRITE = TRUE;


COPY INTO
    @SALES_ANALYTICS_DB.PUBLIC.SALES_ANALYTICS_BACKUP_STAGE/gold/inbound_strategies_booked/
FROM (
    SELECT *
    FROM SALES_ANALYTICS_DB.GOLD.INBOUND_STRATEGIES_BOOKED
)
FILE_FORMAT = (
    FORMAT_NAME = SALES_ANALYTICS_DB.PUBLIC.BACKUP_CSV_FORMAT
)
HEADER = TRUE
OVERWRITE = TRUE;


COPY INTO
    @SALES_ANALYTICS_DB.PUBLIC.SALES_ANALYTICS_BACKUP_STAGE/gold/outbound_prospect_dials/
FROM (
    SELECT *
    FROM SALES_ANALYTICS_DB.GOLD.OUTBOUND_PROSPECT_DIALS
)
FILE_FORMAT = (
    FORMAT_NAME = SALES_ANALYTICS_DB.PUBLIC.BACKUP_CSV_FORMAT
)
HEADER = TRUE
OVERWRITE = TRUE;


COPY INTO
    @SALES_ANALYTICS_DB.PUBLIC.SALES_ANALYTICS_BACKUP_STAGE/gold/outbound_strategies_booked/
FROM (
    SELECT *
    FROM SALES_ANALYTICS_DB.GOLD.OUTBOUND_STRATEGIES_BOOKED
)
FILE_FORMAT = (
    FORMAT_NAME = SALES_ANALYTICS_DB.PUBLIC.BACKUP_CSV_FORMAT
)
HEADER = TRUE
OVERWRITE = TRUE;


COPY INTO
    @SALES_ANALYTICS_DB.PUBLIC.SALES_ANALYTICS_BACKUP_STAGE/gold/sales_details/
FROM (
    SELECT *
    FROM SALES_ANALYTICS_DB.GOLD.SALES_DETAILS
)
FILE_FORMAT = (
    FORMAT_NAME = SALES_ANALYTICS_DB.PUBLIC.BACKUP_CSV_FORMAT
)
HEADER = TRUE
OVERWRITE = TRUE;


-- ============================================================
-- FINAL REPORT BACKUP
-- ============================================================

COPY INTO
    @SALES_ANALYTICS_DB.PUBLIC.SALES_ANALYTICS_BACKUP_STAGE/reports/inbound_setter_report.csv.gz
FROM (
    SELECT *
    FROM SALES_ANALYTICS_DB.GOLD.INBOUND_SETTER_REPORT
)
FILE_FORMAT = (
    FORMAT_NAME = SALES_ANALYTICS_DB.PUBLIC.BACKUP_CSV_FORMAT
)
HEADER = TRUE
SINGLE = TRUE
OVERWRITE = TRUE;


COPY INTO
    @SALES_ANALYTICS_DB.PUBLIC.SALES_ANALYTICS_BACKUP_STAGE/reports/outbound_setter_report.csv.gz
FROM (
    SELECT *
    FROM SALES_ANALYTICS_DB.GOLD.OUTBOUND_SETTER_REPORT
)
FILE_FORMAT = (
    FORMAT_NAME = SALES_ANALYTICS_DB.PUBLIC.BACKUP_CSV_FORMAT
)
HEADER = TRUE
SINGLE = TRUE
OVERWRITE = TRUE;


COPY INTO
    @SALES_ANALYTICS_DB.PUBLIC.SALES_ANALYTICS_BACKUP_STAGE/reports/closer_report.csv.gz
FROM (
    SELECT *
    FROM SALES_ANALYTICS_DB.GOLD.CLOSER_REPORT
)
FILE_FORMAT = (
    FORMAT_NAME = SALES_ANALYTICS_DB.PUBLIC.BACKUP_CSV_FORMAT
)
HEADER = TRUE
SINGLE = TRUE
OVERWRITE = TRUE;


COPY INTO
    @SALES_ANALYTICS_DB.PUBLIC.SALES_ANALYTICS_BACKUP_STAGE/reports/objections_faced_report.csv.gz
FROM (
    SELECT *
    FROM SALES_ANALYTICS_DB.GOLD.OBJECTIONS_FACED_REPORT
)
FILE_FORMAT = (
    FORMAT_NAME = SALES_ANALYTICS_DB.PUBLIC.BACKUP_CSV_FORMAT
)
HEADER = TRUE
SINGLE = TRUE
OVERWRITE = TRUE;

-- Bronze
LIST
@SALES_ANALYTICS_DB.PUBLIC.SALES_ANALYTICS_BACKUP_STAGE/bronze/;

-- Silver
LIST
@SALES_ANALYTICS_DB.PUBLIC.SALES_ANALYTICS_BACKUP_STAGE/silver/;

-- Gold
LIST
@SALES_ANALYTICS_DB.PUBLIC.SALES_ANALYTICS_BACKUP_STAGE/gold/;

-- Reports
LIST
@SALES_ANALYTICS_DB.PUBLIC.SALES_ANALYTICS_BACKUP_STAGE/reports/;

SELECT 'BRONZE' AS LAYER, 'CLOSE_CRM_USERS_RAW' AS OBJECT_NAME,
       COUNT(*) AS ROW_COUNT
FROM SALES_ANALYTICS_DB.BRONZE.CLOSE_CRM_USERS_RAW

UNION ALL

SELECT 'BRONZE', 'CUSTOM_ACTIVITIES_RAW', COUNT(*)
FROM SALES_ANALYTICS_DB.BRONZE.CUSTOM_ACTIVITIES_RAW

UNION ALL

SELECT 'BRONZE', 'LEADS_RAW', COUNT(*)
FROM SALES_ANALYTICS_DB.BRONZE.LEADS_RAW

UNION ALL

SELECT 'BRONZE', 'LEAD_ACTIVITIES_RAW', COUNT(*)
FROM SALES_ANALYTICS_DB.BRONZE.LEAD_ACTIVITIES_RAW

UNION ALL

SELECT 'SILVER', 'CLOSE_CRM_USERS_PROCESSED', COUNT(*)
FROM SALES_ANALYTICS_DB.SILVER.CLOSE_CRM_USERS_PROCESSED

UNION ALL

SELECT 'SILVER', 'CUSTOM_ACTIVITIES', COUNT(*)
FROM SALES_ANALYTICS_DB.SILVER.CUSTOM_ACTIVITIES

UNION ALL

SELECT 'SILVER', 'CUSTOM_ACTIVITIES_ALL_LEADS_DETAILS', COUNT(*)
FROM SALES_ANALYTICS_DB.SILVER.CUSTOM_ACTIVITIES_ALL_LEADS_DETAILS

UNION ALL

SELECT 'SILVER', 'CUSTOM_ACTIVITIES_TRANSIENT', COUNT(*)
FROM SALES_ANALYTICS_DB.SILVER.CUSTOM_ACTIVITIES_TRANSIENT

UNION ALL

SELECT 'SILVER', 'LEADS_ACTIVITIES_SUMMARY', COUNT(*)
FROM SALES_ANALYTICS_DB.SILVER.LEADS_ACTIVITIES_SUMMARY

UNION ALL

SELECT 'SILVER', 'LEADS_ACTIVITIES_SUMMARY_TRANSIENT', COUNT(*)
FROM SALES_ANALYTICS_DB.SILVER.LEADS_ACTIVITIES_SUMMARY_TRANSIENT

UNION ALL

SELECT 'SILVER', 'LEAD_ACTIVITIES_EMAIL', COUNT(*)
FROM SALES_ANALYTICS_DB.SILVER.LEAD_ACTIVITIES_EMAIL

UNION ALL

SELECT 'SILVER', 'LEAD_ACTIVITIES_PROCESSED', COUNT(*)
FROM SALES_ANALYTICS_DB.SILVER.LEAD_ACTIVITIES_PROCESSED

UNION ALL

SELECT 'SILVER', 'LEAD_ACTIVITIES_PROCESSED_TRANSIENT', COUNT(*)
FROM SALES_ANALYTICS_DB.SILVER.LEAD_ACTIVITIES_PROCESSED_TRANSIENT

UNION ALL

SELECT 'GOLD', 'ALL_STRATEGIES_DETAILS', COUNT(*)
FROM SALES_ANALYTICS_DB.GOLD.ALL_STRATEGIES_DETAILS

UNION ALL

SELECT 'GOLD', 'INBOUND_STRATEGIES_BOOKED', COUNT(*)
FROM SALES_ANALYTICS_DB.GOLD.INBOUND_STRATEGIES_BOOKED

UNION ALL

SELECT 'GOLD', 'OUTBOUND_PROSPECT_DIALS', COUNT(*)
FROM SALES_ANALYTICS_DB.GOLD.OUTBOUND_PROSPECT_DIALS

UNION ALL

SELECT 'GOLD', 'OUTBOUND_STRATEGIES_BOOKED', COUNT(*)
FROM SALES_ANALYTICS_DB.GOLD.OUTBOUND_STRATEGIES_BOOKED

UNION ALL

SELECT 'GOLD', 'SALES_DETAILS', COUNT(*)
FROM SALES_ANALYTICS_DB.GOLD.SALES_DETAILS

UNION ALL

SELECT 'REPORT', 'INBOUND_SETTER_REPORT', COUNT(*)
FROM SALES_ANALYTICS_DB.GOLD.INBOUND_SETTER_REPORT

UNION ALL

SELECT 'REPORT', 'OUTBOUND_SETTER_REPORT', COUNT(*)
FROM SALES_ANALYTICS_DB.GOLD.OUTBOUND_SETTER_REPORT

UNION ALL

SELECT 'REPORT', 'CLOSER_REPORT', COUNT(*)
FROM SALES_ANALYTICS_DB.GOLD.CLOSER_REPORT

UNION ALL

SELECT 'REPORT', 'OBJECTIONS_FACED_REPORT', COUNT(*)
FROM SALES_ANALYTICS_DB.GOLD.OBJECTIONS_FACED_REPORT

ORDER BY LAYER, OBJECT_NAME;